/****** Object:  StoredProcedure [ABST_ID].[USP_LOAD_ABST_ACTUAL_CF_TRAN]    Script Date: 28/02/2024 17:45:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [ABST_ID].[USP_LOAD_ABST_ACTUAL_CF_TRAN] @batch_run_id [int],@job_run_id [int],@batchdate [nvarchar](20) AS

TRUNCATE TABLE ABST_ID.ABST_ACTUAL_CF_TRAN ;

DECLARE @ACCT_PERIOD as bigint = CAST(CONCAT(LEFT(@batchdate,4),'0',RIGHT(@batchdate,2)) AS BIGINT);
DECLARE @TotalRecords as integer = (SELECT COUNT(1) FROM FOND_ID.FOND_ETL4_ACTUAL_CF_TRAN_HISTORICAL WHERE ACCT_PERIOD = @ACCT_PERIOD),
		@Count as integer = 0,
		@Loop as integer = 1,
		@BatchSize as integer  = 20000000

PRINT CONCAT('Total Records ',@TotalRecords)
SET @Loop = (@TotalRecords / @BatchSize) + 1

SELECT
		ROW_NUMBER() OVER(ORDER BY TBL.VOUCHER_NO ASC) ROWID,
		TBL.VOUCHER_NO,
		TBL.TOTAL AS COUNTS,
		SUM(TBL.TOTAL) OVER (ORDER BY TBL.VOUCHER_NO) AS CUMULATIVE
INTO #TBL_CHECK
FROM
(
	SELECT VOUCHER_NO,COUNT(1) AS TOTAL 
	FROM FOND_ID.FOND_ETL4_ACTUAL_CF_TRAN_HISTORICAL
	WHERE ACCT_PERIOD = @ACCT_PERIOD
	GROUP BY VOUCHER_NO
) TBL
GROUP BY TBL.VOUCHER_NO,TBL.TOTAL
--ORDER BY TBL.VOUCHER_NO

DECLARE @CountFrom as int = 0,
		@CountTo as int = 0,
		@CountDiff as int = 0,
		@CountToNext as int = 0

PRINT CONCAT('Max Iteration ',@Loop)
WHILE @Count <= @Loop
BEGIN
	PRINT CONCAT('Iteration ',@Count)

	IF @Count = 0
	BEGIN
		SET @CountTo = (SELECT TOP 1 CUMULATIVE FROM #TBL_CHECK WHERE CUMULATIVE <= @BatchSize ORDER BY CUMULATIVE DESC)
	END
	ELSE
	BEGIN
		--SET @CountFrom = (SELECT TOP 1 CUMULATIVE FROM #TBL_CHECK WHERE CUMULATIVE > @CountTo ORDER BY CUMULATIVE ASC)
		SET @CountFrom = @CountTo + 1
		SET @CountTo = (SELECT TOP 1 CUMULATIVE FROM #TBL_CHECK WHERE CUMULATIVE <= (@CountTo+@BatchSize) ORDER BY CUMULATIVE DESC)

		SET @CountDiff = @CountFrom-@CountTo
		IF @CountDiff = 1
		BEGIN
			SET @CountToNext = (SELECT TOP 1 CUMULATIVE FROM #TBL_CHECK WHERE CUMULATIVE > (@CountTo) ORDER BY CUMULATIVE DESC)
			SET @CountTo = @CountToNext
		END
	END

	PRINT CONCAT('Range From ',@CountFrom)
	PRINT CONCAT('Range To ',@CountTo)
	--PRINT ''

	INSERT INTO ABST_ID.ABST_ACTUAL_CF_TRAN (TXN_SK,ENTITY_ID,PAS_NAME,ACCT_PERIOD,POLICY_NO,PRODUCT_CD,BENEFIT_CD,CLAIM_NO,TREATY_IDENTIFIER,SOURCE_PARM_1,SOURCE_PARM_2,SOURCE_PARM_3,VOUCHER_NO,ORG_CCY_CD,AMT_ORG_CCY,AMT_RPT_CCY,SUN_CD,T0,T1,T2,T3,T4,T5,T6,T7,T8,JRNAL_CD,POLICY_IDENTIFIER,COHORT_DT,TXN_DT,RPT_CCY_CD,CR_DR_FLG,JOB_RUN_ID,BATCH_RUN_ID)
	SELECT
		TXN_SK,
		ENTITY_ID,
		PAS_NAME,
		ACCT_PERIOD,
		POLICY_NO,
		PRODUCT_CD,
		BENEFIT_CD,
		CLAIM_NO,
		TREATY_IDENTIFIER,
		SOURCE_PARM_1,
		SOURCE_PARM_2,
		SOURCE_PARM_3,
		VOUCHER_NO,
		ORG_CCY_CD,
		AMT_ORG_CCY,
		AMT_RPT_CCY,
		SUN_CD,
		T0,
		T1,
		T2,
		T3,
		T4,
		T5,
		T6,
		T7,
		T8,
		JRNAL_CD,
		POLICY_IDENTIFIER,
		COHORT_DT,
		TXN_DT,
		RPT_CCY_CD,
		CR_DR_FLG,
		@job_run_id,
		@batch_run_id
	FROM
		(
			SELECT * 
			FROM FOND_ID.FOND_ETL4_ACTUAL_CF_TRAN_HISTORICAL 
			WHERE ACCT_PERIOD = @ACCT_PERIOD
					AND VOUCHER_NO IN (SELECT VOUCHER_NO FROM #TBL_CHECK WHERE CUMULATIVE >= @CountFrom AND CUMULATIVE <= @CountTo)
		) a;

	SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @job_run_id AND BATCH_RUN_ID = @batch_run_id;

	--PRINT CONCAT('Current Iteration ',@Count)
	SET @Count += 1

	PRINT CONCAT('Next Iteration ',@Count)
	PRINT ''
END

DROP TABLE #TBL_CHECK



GO