SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [ABST_ID].[USP_LOAD_ABST_ALLOC_DRIVER_CONFIG] @batch_run_id [int],@job_run_id [int],@batchdate [nvarchar](20) AS

--DELETE FROM ABST_ID.ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER WHERE BATCH_DT = CAST(@batchdate+'01' AS DATE);
TRUNCATE TABLE ABST_ID.ABST_ALLOC_DRIVER_CONFIG;

INSERT INTO ABST_ID.ABST_ALLOC_DRIVER_CONFIG
SELECT
	ENTITY_ID,
	ACCNT_CODE,
	FUND_CD,
	EXPENSE_COMPONENT,
	ALLOCATION_DRIVER,
	@job_run_id,
	@batch_run_id,
	[ACTION],
	USER_PROFILE,
	UPDATE_DATE
FROM
	FOND_ID. FOND_CONFIG_STAG_PLAI_ALLOCATION_MAPPING;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @job_run_id AND BATCH_RUN_ID = @batch_run_id;;;

GO