CREATE PROC [ABST_ID].[USP_LOAD_ETL1_IFRS17_ABST_RI_UC_PROD_ICG_MAP] @batch_run_id [int],@job_run_id [int],@batchdate [nvarchar](20) AS

TRUNCATE TABLE ABST_ID.ABST_RI_UC_PROD_ICG_MAP;

INSERT INTO ABST_ID.ABST_RI_UC_PROD_ICG_MAP 
SELECT
	ENTITY_ID,
	PRODUCT_CD,
	BENEFIT_CD,
	COHORT_YEAR,
	CAST(@batchdate+'01' AS DATE),
	INSURANCE_CONTRACT_GROUP_ID,
	@batch_run_id,
	@job_run_id
FROM STAG_ID.STAG_CONFIG_IFRS17_UC_PROD_ICG_MAP
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @job_run_id AND BATCH_RUN_ID = @batch_run_id;
