CREATE PROC [ABST_ID].[USP_LOAD_ETL1_IFRS17_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;

TRUNCATE TABLE ABST_ID.ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER;

INSERT INTO ABST_ID.ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER 
(
	ENTITY_ID,
	POLICY_NO,
	PRODUCT_CD,
	BENEFIT_CD,
	COHORT_YEAR,
	ENTRY_MONTH,
	INSURANCE_CONTRACT_GROUP_ID,
	SUB_GROUP_ID,
	CB_START_DT,
	CB_END_DT,
	CCY_CD,
	BATCH_DT,
	BATCH_RUN_ID,
	JOB_RUN_ID
)
SELECT
	ENTITY_ID,
	POLICY_NO,
	PRODUCT_CD,
	BENEFIT_CD,
	COHORT_YEAR,
	ENTRY_MONTH,
	INSURANCE_CONTRACT_GROUP_ID,
	SUB_GROUP_ID,
	CB_START_DT,
	CB_END_DT,
	CCY_CD,
	CAST(@BATCHDATESTR+'01' AS DATE),
	@BATCH_RUN_ID,
	@JOB_RUN_ID
FROM [FOND_ID].[FOND_IFRS17_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER]
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @JOB_RUN_ID AND BATCH_RUN_ID = @BATCH_RUN_ID;


