CREATE PROC [ABST_ID].[USP_LOAD_ETL1_IFRS17_ABST_L2_CODE_GHO_ROLLUP] @batch_run_id [int],@job_run_id [int],@batchdate [nvarchar](20) AS

TRUNCATE TABLE ABST_ID.ABST_L2_CODE_GHO_ROLLUP;

INSERT INTO ABST_ID.ABST_L2_CODE_GHO_ROLLUP 
SELECT
	ENTITY_ID,
	LBU_PARAMETER,
	LBU_PARAMETER_CODE,
	LBU_PARAMETER_NAME,
	ANALYSIS_DIMENSION,
	LOOK_UP_CODE,
	GHO_CUST_CD_LOBINS,
	CAST(@batchdate+'01' AS DATE),
	@batch_run_id,
	@job_run_id
FROM [FOND_ID].[FOND_IFRS17_ABST_L2_GHO_ROLLUP]
;



SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @job_run_id AND BATCH_RUN_ID = @batch_run_id;




