CREATE PROC [ABST_ID].[USP_LOAD_ETL1_IFRS17_ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER] @batch_run_id [int],@job_run_id [int],@batchdate [nvarchar](20) AS

TRUNCATE TABLE ABST_ID.ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER;

INSERT INTO ABST_ID.ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER 
SELECT
	ENTITY_ID,
	POLICY_NUMBER,
	PRODUCT_CODE,
	BENEFIT_CODE,
	COHORT_YEAR,
	ENTRY_MONTH,
	INSURANCE_CONTRACT_GROUP_ID,
	SUB_GROUP_ID,
	CB_START_DATE,
	CB_END_DATE,
	CURRENCY,
	CAST(@batchdate+'01' AS DATE),
	@batch_run_id,
	@job_run_id
FROM [FOND_ID].[FOND_IFRS17_ABST_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER]
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @job_run_id AND BATCH_RUN_ID = @batch_run_id;




