CREATE PROC [ABST_ID].[USP_LOAD_ETL1_IFRS17_RI_PROD_TREATY_MAP_MASTER] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;

TRUNCATE TABLE ABST_ID.ABST_RI_PROD_TREATY_MAP_MASTER;

INSERT INTO ABST_ID.ABST_RI_PROD_TREATY_MAP_MASTER
(
	ENTITY_ID,
	PRODUCT_CD,
	BENEFIT_CD,
	TREATY_ID,
	TREATY_NAME,
	MASTER_TREATY_ID,
	TREATY_EFF_DT,
	TREATY_END_DT,
	--RI_STRUCTURE,
	PREM_GUARANTEE,
	GUARANTEE_TERM,
	RI_CONTRACT_BOUNDARY,
	RI_PORTFOLIO_GROUP,
	MEASUREMENT_MODEL,
	RI_CCY_CD,
	SERVICE_FLG,
	QS_PERC,
	INVESTMENT_COMPONENT,
	COUNTERPARTY_ID,
	BATCH_RUN_ID,
	JOB_RUN_ID
)
SELECT
	ENTITY_ID,
	PRODUCT_CD,
	BENEFIT_CD,
	TREATY_ID,
	TREATY_NAME,
	MASTER_TREATY_ID,
	TREATY_EFF_DT,
	TREATY_END_DT,
	--RI_STRUCTURE,
	PREM_GUARANTEE,
	GUARANTEE_TERM,
	RI_CONTRACT_BOUNDARY,
	RI_PORTFOLIO_GROUP,
	MEASUREMENT_MODEL,
	RI_CCY_CD,
	SERVICE_FLG,
	QS_PERC,
	INVESTMENT_COMPONENT,
	COUNTERPARTY_ID,
	@BATCH_RUN_ID,
	@JOB_RUN_ID

--FROM FOND_ID.FOND_IFRS17_ABST_PROD_TREATY_MAP_MASTER
FROM STAG_ID.STAG_CONFIG_IFRS17_PROD_TREATY_MAP_MASTER
;
 
SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @JOB_RUN_ID AND BATCH_RUN_ID = @BATCH_RUN_ID;

