CREATE PROC [ABST_ID].[USP_LOAD_ETL1_IFRS17_ABST_PRODUCT_CONFIG] @batch_run_id [int],@job_run_id [int],@batchdate [nvarchar](20) AS

TRUNCATE TABLE ABST_ID.ABST_PRODUCT_CONFIG;

INSERT INTO ABST_ID.ABST_PRODUCT_CONFIG 
SELECT
	ENTITY_ID,
	PRODUCT_CODE,
	BENEFIT_CODE,
	SERVICE_FLAG,
	CAST(@batchdate+'01' AS DATE),
	@batch_run_id,
	@job_run_id
FROM [FOND_ID].[FOND_IFRS17_PRODUCT_CONFIG]
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @job_run_id AND BATCH_RUN_ID = @batch_run_id;




