CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_INSURANCE_CONTRACT_GROUP_MASTER] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;

TRUNCATE TABLE FOND_ID.FOND_IFRS17_INSURANCE_CONTRACT_GROUP_MASTER;

INSERT INTO FOND_ID.FOND_IFRS17_INSURANCE_CONTRACT_GROUP_MASTER 
SELECT DISTINCT
   'IAI' AS ENTITY_ID
 , icc.INSURANCE_CONTRACT_GROUP_ID
 , icc.PORTFOLIO_GROUP
 , icc.COHORT_YEAR
 , icc.SET_OF_CONTRACT
 , icc.PROFITABILITY_GROUP_PRICING
 , icc.CCY_CD
 , icc.MEASUREMENT_MODEL
 , icc.NATURE
 , pds.OCI_OPTION
 , icc.L1
 , @BATCH_MASTER_ID AS BATCH_MASTER_ID 
 , @BATCH_RUN_ID AS BATCH_RUN_ID 
 , @JOB_MASTER_ID AS JOB_MASTER_ID
 , @JOB_RUN_ID AS JOB_RUN_ID  
 , @BATCHDATESTR AS BATCHDATE
 , @GMT_START_DTTM AS ETL_PROCESS_DATE_TIME 

FROM STAG_ID.STAG_CONFIG_IFRS17_ICG_CONFIG AS icc

LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_PORTFOLIO_DETAILS AS pds 
ON TRIM(icc.PORTFOLIO_GROUP) = TRIM(pds.PORTFOLIO_GROUP)
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @JOB_RUN_ID AND BATCH_RUN_ID = @BATCH_RUN_ID;


