CREATE PROC [FOND_ID].[USP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@PRD_ID [INTEGER] AS

BEGIN
DECLARE @V_START			DATETIME,
		@V_END				DATETIME,
		@V_DURATION			DATETIME,
		@V_FUNCTION_NAME	VARCHAR(100),
		@V_DESCRIPTION		VARCHAR(100),
		@V_CMD				VARCHAR(100),
		@V_SEQNO			INTEGER,
		@V_PRD_ID			INTEGER,
		@V_CREATED_DATE		DATETIME,
		@V_START_DATE		DATE,
		@V_END_DATE			DATE,
------START GET RUN ID DETAIL FROM ABC------
 @BATCH_MASTER_ID    VARCHAR(20) = 0,
 @BATCH_RUN_ID       VARCHAR(20) = 0,
 @JOB_MASTER_ID      VARCHAR(20) = 0,
 @JOB_RUN_ID         VARCHAR(20) = 0,
 @GMT_START_DTTM     VARCHAR(20) = GETDATE();
 
EXEC STAG_ID.USP_GetRunIdReturn
  @JobName        = @JOBNAMESTR,
  @BATCH_MASTER_ID = @BATCH_MASTER_ID OUTPUT,
  @BATCH_RUN_ID    = @BATCH_RUN_ID OUTPUT,
  @JOB_MASTER_ID   = @JOB_MASTER_ID OUTPUT,
  @JOB_RUN_ID      = @JOB_RUN_ID OUTPUT,
  @GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;
------END GET RUN ID DETAIL FROM ABC--------- 	

------set variable----------------
SET @BATCHDATESTR = CAST(EOMONTH(CAST(CONCAT(SUBSTRING(@BATCHDATESTR,0,5),'-',SUBSTRING(@BATCHDATESTR,5,2),'-01') AS DATE)) AS VARCHAR(10));
SET @PRD_ID = CONCAT(SUBSTRING(CAST(@PRD_ID AS VARCHAR),0,5),SUBSTRING(CAST(@PRD_ID AS VARCHAR),5,2),'01');

SET @V_FUNCTION_NAME = 'FOND_ID.USP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC';
SET @V_SEQNO = 1;
SET @V_START_DATE = CONVERT(DATE, CONVERT(CHAR(10), @PRD_ID));
SET @V_START = CURRENT_TIMESTAMP;
SET @V_DESCRIPTION = CONCAT('Start ', @V_FUNCTION_NAME, ' : ', @V_START_DATE)

-----------------------------
	--- DROP ALL TEMPORARY TABLES
	-----------------------------
	SET @V_SEQNO = @V_SEQNO + 1;
	SET @V_START = CURRENT_TIMESTAMP;
	SET @V_DESCRIPTION = CONCAT('DROP ALL TEMPORARY TABLES : ', @V_START);

	INSERT INTO STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE, FUNC_NAME, SEQNO, [DESCRIPTION])
	VALUES (@V_START, @V_FUNCTION_NAME, @V_SEQNO, @V_DESCRIPTION);

	IF OBJECT_ID('tempdb.dbo.#TMP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC_IND', 'U') IS NOT NULL DROP TABLE tempdb.dbo.#TMP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC_IND;

----------------------------------------------
--create temp table tempdb.dbo.#TMP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC_IND
-----------------------------------------------
		
SET @V_SEQNO = @V_SEQNO + 1;
SET @V_START = CURRENT_TIMESTAMP;
SET @V_DESCRIPTION = CONCAT('create temp table tempdb.dbo.#TMP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC_IND : ', @V_START);

INSERT INTO STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE, FUNC_NAME, SEQNO, [DESCRIPTION])
VALUES (@V_START, @V_FUNCTION_NAME, @V_SEQNO, @V_DESCRIPTION);

--ENHANCED BY DYAH 24/06
CREATE TABLE tempdb.dbo.#TMP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC_IND
WITH
(
	DISTRIBUTION = HASH(CHDRNUM)
	,CLUSTERED INDEX(CHDRNUM)
)
as 
SELECT B.*, 
CASE WHEN YEAR(B.[CB_START_DT]) <= YEAR(CAST(@BATCHDATESTR AS DATE))-1 THEN 'SOP' ELSE 'EOP' END AS [IND]
FROM (SELECT A.*, ROW_NUMBER() OVER(PARTITION BY [CHDRNUM],[PRODUCT_CD],[BENEFIT_CD] ORDER BY [CB_START_DT] DESC) AS [RN]
						FROM (SELECT [CHDRNUM],[PRODUCT_CD],[BENEFIT_CD], [CB_START_DT]
								FROM FOND_ID.FOND_IFRS17_TRADITIONAL_ACT_USED_HIS
								WHERE BACKUP_BATCHDATE >= CAST(CONCAT(YEAR(CAST(@BATCHDATESTR AS DATE))-1,'-12-31') AS DATE)) AS A) AS B
				WHERE B.[RN] = '1'

INSERT INTO STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,[DESCRIPTION])
VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

BEGIN TRY
DROP TABLE [FOND_ID].[FOND_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC];
PRINT 'Table exist, dropping table..'
END TRY
BEGIN CATCH
	PRINT 'Table does not exists..'
END CATCH

BEGIN TRY
CREATE TABLE [FOND_ID].[FOND_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC]

WITH
	(
	  DISTRIBUTION = HASH(CHDRNUM),
	  HEAP
	) AS

WITH SOP AS (
	SELECT * FROM (
		SELECT * , ROW_NUMBER() OVER(PARTITION BY CHDRNUM, PRODUCT_CD, BENEFIT_CD ORDER BY BACKUP_BATCHDATE ASC) AS ROW_NUMBER
		FROM FOND_ID.FOND_IFRS17_TRADITIONAL_ACT_USED_HIS
		WHERE BACKUP_BATCHDATE >= CAST(CONCAT(YEAR(CAST(@BATCHDATESTR AS DATE))-1,'-12-31') AS DATE) --UPDATE SOP to gether 2 digit month
		AND CONCAT( YEAR(BACKUP_BATCHDATE),SUBSTRING(CAST(BACKUP_BATCHDATE AS CHAR),6,2)) <= CONCAT(YEAR(CAST(@BATCHDATESTR AS DATE)),SUBSTRING(CAST(@BATCHDATESTR AS CHAR),6,2))
	)TMP WHERE TMP.ROW_NUMBER = '1'
),

EOP AS (
	 SELECT *
  FROM FOND_ID.FOND_IFRS17_TRADITIONAL_ACT_USED_HIS
  WHERE YEAR(BACKUP_BATCHDATE) = YEAR(CAST(@BATCHDATESTR AS DATE)) AND MONTH(BACKUP_BATCHDATE) = MONTH(CAST(@BATCHDATESTR AS DATE))
)

SELECT DISTINCT
	SOP.[PRODUCT_CD]
			  ,SOP.[BENEFIT_CD] --Altered
			  ,SOP.[CHDRNUM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CRTABLE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CRTABLE]
					 END
				ELSE
					 SOP.[CRTABLE] END) AS [CRTABLE]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[ANBCCD]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[ANBCCD]
					 END
				ELSE
					 SOP.[ANBCCD] END) AS [ANBCCD]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[SEX]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[SEX]
					 END
				ELSE
					 SOP.[SEX] END) AS [SEX]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[MORTCLS]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[MORTCLS]
					 END
				ELSE
					 SOP.[MORTCLS] END) AS [MORTCLS]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[PRMTRM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[PRMTRM]
					 END
				ELSE
					 SOP.[PRMTRM] END) AS [PRMTRM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[RSKTRM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[RSKTRM]
					 END
				ELSE
					 SOP.[RSKTRM] END) AS [RSKTRM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[PREMI]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[PREMI]
					 END
				ELSE
					 SOP.[PREMI] END) AS [PREMI]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[BILLFREQ]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[BILLFREQ]
					 END
				ELSE
					 SOP.[BILLFREQ] END) AS [BILLFREQ]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[SUMINS]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[SUMINS]
					 END
				ELSE
					 SOP.[SUMINS] END) AS [SUMINS]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[TOTBON]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[TOTBON]
					 END
				ELSE
					 SOP.[TOTBON] END) AS [TOTBON]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[PTDATE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[PTDATE]
					 END
				ELSE
					 SOP.[PTDATE] END) AS [PTDATE]
			  ,(CASE WHEN (SOP.[HOISSDTE] = '' OR SOP.[HOISSDTE] IS NULL) 
				THEN  
					COALESCE(EOP.[HOISSDTE],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
					THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[HOISSDTE]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[HOISSDTE]
						END
					ELSE
						SOP.[HOISSDTE] END END) AS [HOISSDTE]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CRRCD]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CRRCD]
					 END
				ELSE
					 SOP.[CRRCD] END) AS [CRRCD]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[RCESDTE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[RCESDTE]
					 END
				ELSE
					 SOP.[RCESDTE] END) AS [RCESDTE]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CNTCURR]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CNTCURR]
					 END
				ELSE
					 SOP.[CNTCURR] END) AS [CNTCURR]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[STATCODE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[STATCODE]
					 END
				ELSE
					 SOP.[STATCODE] END) AS [STATCODE]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CURRFROM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CURRFROM]
					 END
				ELSE
					 SOP.[CURRFROM] END) AS [CURRFROM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[ZLINSTPREM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[ZLINSTPREM]
					 END
				ELSE
					 SOP.[ZLINSTPREM] END) AS [ZLINSTPREM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[BPAYTY]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[BPAYTY]
					 END
				ELSE
					 SOP.[BPAYTY] END) AS [BPAYTY]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[BPAYNY]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[BPAYNY]
					 END
				ELSE
					 SOP.[BPAYNY] END) AS [BPAYNY]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[SLSCNL]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[SLSCNL]
					 END
				ELSE
					 SOP.[SLSCNL] END) AS [SLSCNL]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[BILLCHNL]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[BILLCHNL]
					 END
				ELSE
					 SOP.[BILLCHNL] END) AS [BILLCHNL]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[ZPDFSURR]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[ZPDFSURR]
					 END
				ELSE
					 SOP.[ZPDFSURR] END) AS [ZPDFSURR]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CLTPHONE01]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CLTPHONE01]
					 END
				ELSE
					 SOP.[CLTPHONE01] END) AS [CLTPHONE01]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CLTPHONE02]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CLTPHONE02]
					 END
				ELSE
					 SOP.[CLTPHONE02] END) AS [CLTPHONE02]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[LIFCNUM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[LIFCNUM]
					 END
				ELSE
					 SOP.[LIFCNUM] END) AS [LIFCNUM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[AGNTNUM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[AGNTNUM]
					 END
				ELSE
					 SOP.[AGNTNUM] END) AS [AGNTNUM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[DTEAPP]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[DTEAPP]
					 END
				ELSE
					 SOP.[DTEAPP] END) AS [DTEAPP]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[DTETRM]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[DTETRM]
					 END
				ELSE
					 SOP.[DTETRM] END) AS [DTETRM]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[TSALESUNT]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[TSALESUNT]
					 END
				ELSE
					 SOP.[TSALESUNT] END) AS [TSALESUNT]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[REPORTAG]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[REPORTAG]
					 END
				ELSE
					 SOP.[REPORTAG] END) AS [REPORTAG]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[COLUMN_NULL1]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[COLUMN_NULL1]
					 END
				ELSE
					 SOP.[COLUMN_NULL1] END) AS [ClaimWVR]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[COLUMN_ZERO1]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[COLUMN_ZERO1]
					 END
				ELSE
					 SOP.[COLUMN_ZERO1] END) AS [ClaimWV_RES]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[FUND]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[FUND]
					 END
				ELSE
					 SOP.[FUND]END) AS [PCA_CLASS1]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[COLUMN_NULL2]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[COLUMN_NULL2]
					 END
				ELSE
					 SOP.[COLUMN_NULL2] END) AS [WVR_DATESTART]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CLTADDR04]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CLTADDR04]
					 END
				ELSE
					 SOP.[CLTADDR04] END) AS [CLTADDR04]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CLTADDR05]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CLTADDR05]
					 END
				ELSE
					 SOP.[CLTADDR05] END) AS [CLTADDR05]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[COLUMN_ZERO2]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[COLUMN_ZERO2]
					 END
				ELSE
					 SOP.[COLUMN_ZERO2] END) AS [CLAIM_RES]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CLTDOB]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CLTDOB]
					 END
				ELSE
					 SOP.[CLTDOB] END) AS [CLTDOB]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[MEDFLG]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[MEDFLG]
					 END
				ELSE
					 SOP.[MEDFLG] END) AS [MEDFLG]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[PLAN_TRAD]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[PLAN_TRAD]
					 END
				ELSE
					 SOP.[PLAN_TRAD] END) AS [PLAN_TRAD]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[MODE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[MODE]
					 END
				ELSE
					 SOP.[MODE] END) AS [MODE]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[PRUBP]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[PRUBP]
					 END
				ELSE
					 SOP.[PRUBP] END) AS [PRUBP]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CHANNEL]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CHANNEL]
					 END
				ELSE
					 SOP.[CHANNEL] END) AS [CHANNEL]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[SRCEBUS]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[SRCEBUS]
					 END
				ELSE
					 SOP.[SRCEBUS] END) AS [SRCEBUS]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[REASONCD]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[REASONCD]
					 END
				ELSE
					 SOP.[REASONCD] END) AS [REASONCD]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[LONGDESC]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[LONGDESC]
					 END
				ELSE
					 SOP.[LONGDESC] END) AS [LONGDESC]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[COLUMN 48]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[COLUMN 48]
					 END
				ELSE
					 SOP.[COLUMN 48] END) AS [REGION_INDICATOR]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[PRUSEHAT_SOLUTION_PLAN_TYPE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[PRUSEHAT_SOLUTION_PLAN_TYPE]
					 END
				ELSE
					 SOP.[PRUSEHAT_SOLUTION_PLAN_TYPE] END) AS [PRUSEHAT_SOLUTION_PLAN_TYPE]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[SUBSTANDARD_LOADING]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[SUBSTANDARD_LOADING]
					 END
				ELSE
					 SOP.[SUBSTANDARD_LOADING] END) AS [SUBSTANDARD_LOADING]
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CAMPAIGN_FLAG]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CAMPAIGN_FLAG]
					 END
				ELSE
					 SOP.[CAMPAIGN_FLAG] END) AS [CAMPAIGN_FLAG] --> Added in v4
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[TOTCLAIMS]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[TOTCLAIMS]
					 END
				ELSE
					 SOP.[TOTCLAIMS] END) AS [TOTCLAIMS] -- updated by dyah 09/08/2022
			  ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[STAT_SECT]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[STAT_SECT]
					 END
				ELSE
					 SOP.[STAT_SECT] END) AS [STAT_SECT] -- updated by dyah 09/08/2022
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[REN_PREM_IND]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[REN_PREM_IND]
					 END
				ELSE
					 SOP.[REN_PREM_IND] END) AS [REN_PREM_IND] -- updated by dyah 09/08/2022
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[FAMPLAN_IND]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[FAMPLAN_IND]
					 END
				ELSE
					 SOP.[FAMPLAN_IND] END) AS [FAMPLAN_IND] -- updated by dyah 09/08/2022
			 -- start DARA 230401
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[LOOKUP_CODE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[LOOKUP_CODE]
					 END
				ELSE
					 SOP.[LOOKUP_CODE] END) AS [LOOKUP_CODE]
			 -- end DARA 230401
			 -- ALDO 202312
			 ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CV_BALANCE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CV_BALANCE]
					 END
				ELSE
					 SOP.[CV_BALANCE] END) AS [CV_BALANCE]
			 -- ALDO 202312
			 ,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[E-SUBMISSION_E-POLICY_AND_MAILFLAG]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[E-SUBMISSION_E-POLICY_AND_MAILFLAG]
					 END
				ELSE
					 SOP.[E-SUBMISSION_E-POLICY_AND_MAILFLAG] END) AS [E-SUBMISSION_E-POLICY_AND_MAILFLAG]
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[WP_FLAG]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[WP_FLAG]
					 END
				ELSE
					 SOP.[WP_FLAG] END) AS [WP_FLAG]
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[CAMP_CODE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[CAMP_CODE]
					 END
				ELSE
					 SOP.[CAMP_CODE] END) AS [CAMP_CODE]
			,(CASE WHEN [BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y'
				THEN
					 CASE WHEN INDICATOR.[IND] = 'SOP'
					 THEN
						 SOP.[RBP_STATE]
					 WHEN INDICATOR.[IND] = 'EOP'
					 THEN
						 EOP.[RBP_STATE]
					 END
				ELSE
					 SOP.[RBP_STATE] END) AS [RBP_STATE]
			  ,(CASE WHEN (SOP.[IFRS_ONEROUS_GRP] = '' OR SOP.[IFRS_ONEROUS_GRP] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_ONEROUS_GRP],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
					THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_ONEROUS_GRP]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_ONEROUS_GRP]
						END
					ELSE
						SOP.[IFRS_ONEROUS_GRP] END END) AS [IFRS_ONEROUS_GRP]
			  ,(CASE WHEN (SOP.[IFRS_CY_GRP] = '' OR SOP.[IFRS_CY_GRP] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_CY_GRP],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
					THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_CY_GRP]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_CY_GRP]
						END
					ELSE
						SOP.[IFRS_CY_GRP] END END) AS [IFRS_CY_GRP]
			  ,(CASE WHEN (SOP.[IFRS_PORT_GRP] = '' OR SOP.[IFRS_PORT_GRP] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_PORT_GRP],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_PORT_GRP]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_PORT_GRP]
						END
					ELSE
						SOP.[IFRS_PORT_GRP] END END) AS [IFRS_PORT_GRP]
			  ,(CASE WHEN (SOP.[IFRS_MEASURE_MODEL] = '' OR SOP.[IFRS_MEASURE_MODEL] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_MEASURE_MODEL],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_MEASURE_MODEL]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_MEASURE_MODEL]
						END
					ELSE
						SOP.[IFRS_MEASURE_MODEL] END END) AS [IFRS_MEASURE_MODEL]
			  ,(CASE WHEN (SOP.[BASIC_ENTRY_YEAR] = '' OR SOP.[BASIC_ENTRY_YEAR] IS NULL) 
				THEN  
					COALESCE(EOP.[BASIC_ENTRY_YEAR],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[BASIC_ENTRY_YEAR]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[BASIC_ENTRY_YEAR]
						END
					ELSE
						SOP.[BASIC_ENTRY_YEAR] END END) AS [BASIC_ENTRY_YEAR]
			  ,(CASE WHEN (SOP.[BASIC_ENTRY_MONTH] = '' OR SOP.[BASIC_ENTRY_MONTH] IS NULL) 
				THEN  
					COALESCE(EOP.[BASIC_ENTRY_MONTH],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[BASIC_ENTRY_MONTH]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[BASIC_ENTRY_MONTH]
						END
					ELSE
						SOP.[BASIC_ENTRY_MONTH] END END) AS [BASIC_ENTRY_MONTH]
			  ,(CASE WHEN (SOP.[IFRS_CB_TERM_M] = '' OR SOP.[IFRS_CB_TERM_M] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_CB_TERM_M],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_CB_TERM_M]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_CB_TERM_M]
						END
					ELSE
						SOP.[IFRS_CB_TERM_M] END END) AS [IFRS_CB_TERM_M]
			  ,(CASE WHEN (SOP.[MTHS_TO_SALE] = '' OR SOP.[MTHS_TO_SALE] IS NULL) 
				THEN  
					COALESCE(EOP.[MTHS_TO_SALE],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[MTHS_TO_SALE]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[MTHS_TO_SALE]
						END
					ELSE
						SOP.[MTHS_TO_SALE] END END) AS [MTHS_TO_SALE]
			  ,(CASE WHEN (SOP.[IFRS_ICG_ID] = '' OR SOP.[IFRS_ICG_ID] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_ICG_ID],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_ICG_ID]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_ICG_ID]
						END
					ELSE
						SOP.[IFRS_ICG_ID] END END) AS [IFRS_ICG_ID]
			  ,(CASE WHEN (SOP.[IFRS_ICG_ID_PROPHET] = '' OR SOP.[IFRS_ICG_ID_PROPHET] IS NULL) 
				THEN  
					COALESCE(EOP.[IFRS_ICG_ID_PROPHET],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[IFRS_ICG_ID_PROPHET]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[IFRS_ICG_ID_PROPHET]
						END
					ELSE
						SOP.[IFRS_ICG_ID_PROPHET] END END) AS [IFRS_ICG_ID_PROPHET]
			  ,(CASE WHEN (SOP.[SUB_GROUP_ID] = '' OR SOP.[SUB_GROUP_ID] IS NULL) 
				THEN  
					COALESCE(EOP.[SUB_GROUP_ID],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[SUB_GROUP_ID]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[SUB_GROUP_ID]
						END
					ELSE
						SOP.[SUB_GROUP_ID] END END) AS [SUB_GROUP_ID]
			  ,(CASE WHEN (SOP.[ENTITY_ID] = '' OR SOP.[ENTITY_ID] IS NULL) 
				THEN  
					COALESCE(EOP.[ENTITY_ID],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[ENTITY_ID]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[ENTITY_ID]
						END
					ELSE
						SOP.[ENTITY_ID] END END) AS [ENTITY_ID]
			  ,(CASE WHEN (SOP.[CB_START_DT] = '' OR SOP.[CB_START_DT] IS NULL) 
				THEN  
					COALESCE(EOP.[CB_START_DT],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[CB_START_DT]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[CB_START_DT]
						END
					ELSE
						SOP.[CB_START_DT] END END) AS [CB_START_DT]
			  ,(CASE WHEN (SOP.[CB_END_DT] = '' OR SOP.[CB_END_DT] IS NULL) 
				THEN  
					COALESCE(EOP.[CB_END_DT],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[CB_END_DT]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[CB_END_DT]
						END
					ELSE
						SOP.[CB_END_DT] END END) AS [CB_END_DT]
			  ,(CASE WHEN (SOP.[REL_INSURANCE_CONTRACT_GROUP_ID] = '' OR SOP.[REL_INSURANCE_CONTRACT_GROUP_ID] IS NULL) 
				THEN  
					COALESCE(EOP.[REL_INSURANCE_CONTRACT_GROUP_ID],'')
				ELSE 
					CASE WHEN ([BOUND_BY_TERMINATION_PROVISION] = 'Y' OR [BOUND_BY_REPRICE] = 'Y')
						THEN 
						CASE WHEN INDICATOR.[IND] = 'SOP'
						THEN 
							SOP.[REL_INSURANCE_CONTRACT_GROUP_ID]
						WHEN INDICATOR.[IND] = 'EOP'
						THEN 
							EOP.[REL_INSURANCE_CONTRACT_GROUP_ID]
						END
					ELSE
						SOP.[REL_INSURANCE_CONTRACT_GROUP_ID] END END) AS [REL_INSURANCE_CONTRACT_GROUP_ID]
			  ,CASE WHEN EOP.[STATCODE] = 'IF' AND EOP.[BILLCHNL] = 'A'
					THEN 'PH'
					ELSE EOP.[STATCODE]
			  END AS [STATCODE_EOP],
	@BATCH_MASTER_ID AS BATCH_MASTER_ID, 
	@BATCH_RUN_ID AS BATCH_RUN_ID,
	@JOB_MASTER_ID AS JOB_MASTER_ID,
	@JOB_RUN_ID  AS JOB_RUN_ID,
	@BATCHDATESTR AS BATCHDATE,
	@GMT_START_DTTM AS ETL_PROCESS_DATE_TIME
FROM  SOP
LEFT JOIN EOP ON SOP.[CHDRNUM] = EOP.[CHDRNUM] AND SOP.PRODUCT_CD = EOP.PRODUCT_CD AND SOP.BENEFIT_CD = EOP.BENEFIT_CD
/*LEFT JOIN (
	SELECT DISTINCT CHDRNUM,PRODUCT_CD,BENEFIT_CD
	FROM FOND_ID.FOND_IFRS17_TRADITIONAL_ACT_USED_HIS
	WHERE BACKUP_BATCHDATE = CAST(CONCAT(YEAR(CAST(@BATCHDATESTR AS DATE))-1,'-12-31') AS DATE)
) AS REMOVE_POLICY_SOP 
ON SOP.CHDRNUM = REMOVE_POLICY_SOP.CHDRNUM
	AND SOP.PRODUCT_CD = REMOVE_POLICY_SOP.PRODUCT_CD
	AND SOP.BENEFIT_CD = REMOVE_POLICY_SOP.BENEFIT_CD*/
LEFT JOIN (SELECT * FROM STAG_ID.STAG_CONFIG_IFRS17_CB_MAPPING  
			WHERE SYSTEM = 'Life Asia') CB_MAPPING
ON SOP.PRODUCT_CD = CB_MAPPING.PRODUCT_CD
LEFT JOIN tempdb.dbo.#TMP_IFRS17_TRADITIONAL_ACT_USED_AOM_5ABC_IND INDICATOR
ON SOP.[CHDRNUM] = INDICATOR.[CHDRNUM] AND SOP.PRODUCT_CD = INDICATOR.PRODUCT_CD AND SOP.BENEFIT_CD = INDICATOR.BENEFIT_CD
--WHERE SOP.BACKUP_BATCHDATE > CAST(CONCAT(YEAR(CAST(@BATCHDATESTR AS DATE))-1,'-12-31') AS DATE) 
--AND REMOVE_POLICY_SOP.CHDRNUM IS NULL;


END TRY
	BEGIN CATCH
	    DECLARE @ErrorMessage AS NVARCHAR(1000) = ERROR_MESSAGE()
		DECLARE @ErrorSeverity AS INT = ERROR_SEVERITY()
		DECLARE @ErrorState AS INT = ERROR_STATE()

 		--IF @@TRANCOUNT > 0  
		--	ROLLBACK TRAN; 
		
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_END 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	='Error execution for function on ' 
							+ @V_FUNCTION_NAME + ' at ' + convert(varchar,@V_START,121) 
							+ ' with Error Message : ' + ERROR_MESSAGE();
		PRINT @V_DESCRIPTION;
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION) VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
		RAISERROR(@ErrorMessage,@ErrorSeverity,@ErrorState)
	
	END CATCH

END
