CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_L1_CODE_GHO_ROLLUP_ENTITY] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@ENTITY [NVARCHAR](2000),@P_PRD_ID [integer] AS
--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();
DECLARE @v_SQL_1 NVARCHAR(MAX);
DECLARE @v_SQL_2 NVARCHAR(MAX);

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn_ENTITY
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT
,@ENTITY = @ENTITY;

SET @v_SQL_1='TRUNCATE TABLE ABST_ID'+@ENTITY+'.ABST_L1_CODE_GHO_ROLLUP;'

EXEC (@v_SQL_1)

SET @v_SQL_2='
INSERT INTO ABST_ID'+@ENTITY+'.ABST_L1_CODE_GHO_ROLLUP
(
	ENTITY_ID,
	LBU_PARAMETER,
	LBU_PARAMETER_CD,
	LBU_PARAMETER_NAME,
	ANALYSIS_DIMENSION,
	LOOK_UP_CD,
	GHO_CUST_CD_ENTITY,
	GHO_CUST_CD_LOBT,
	BATCH_DT,
	BATCH_RUN_ID,
	JOB_RUN_ID
)
SELECT
	ENTITY_ID,
	LBU_PARAMETER,
	LBU_PARAMETER_CD,
	LBU_PARAMETER_NAME,
	ANALYSIS_DIMENSION,
	LOOK_UP_CD,
	GHO_CUST_CD_ENTITY,
	GHO_CUST_CD_LOBT,
	BATCH_DT,
	'+@BATCH_RUN_ID+',
	'+@JOB_RUN_ID+'
FROM (
		SELECT '''+@ENTITY+''' AS ENTITY_ID,
			LBU_PARAMETER,
			LBU_PARAMETER_CD,
			LBU_PARAMETER_NAME,
			ANALYSIS_DIMENSION,
			LOOK_UP_CD,
			GHO_CUST_CD_ENTITY,
			GHO_CUST_CD_LOBT,
			BATCH_DT
		FROM (
		SELECT CASE 
			WHEN LBU_PARAMETER_CD LIKE ''%CON%'' THEN ''IAC'' 
			WHEN LBU_PARAMETER_CD LIKE ''%SHA%'' THEN ''IAS''
			WHEN LBU_PARAMETER_CD LIKE ''%B71%'' THEN ''IAS''
			ELSE ''ERROR'' END FLAG
			, ABST_L1_CODE_GHO_ROLLUP.* FROM ABST_ID.ABST_L1_CODE_GHO_ROLLUP
		) A
		WHERE FLAG='''+@ENTITY+'''
		UNION ALL
		SELECT '''+@ENTITY+''' AS ENTITY_ID,
			LBU_PARAMETER,
			LBU_PARAMETER_CD,
			LBU_PARAMETER_NAME,
			ANALYSIS_DIMENSION,
			LOOK_UP_CD,
			GHO_CUST_CD_ENTITY,
			GHO_CUST_CD_LOBT,
			BATCH_DT
		FROM ABST_ID.ABST_L1_CODE_GHO_ROLLUP
		WHERE LBU_PARAMETER_CD = CASE WHEN '''+@ENTITY+''' = ''IAC'' 
		THEN ''PRPSURSHAUL'' ELSE ''PRNONPXLCON'' END
) ABST_L1_CODE_GHO_ROLLUP'

EXEC (@v_SQL_2)

