CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_INSURANCE_CONTRACT_GROUP_MASTER_ENTITY] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@ENTITY [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();
DECLARE @v_SQL_1 NVARCHAR(MAX);
DECLARE @v_SQL_2 NVARCHAR(MAX);

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn_ENTITY
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT
,@ENTITY = @ENTITY;

SET @v_SQL_1='TRUNCATE TABLE ABST_ID'+@ENTITY+'.ABST_INSURANCE_CONTRACT_GROUP_MASTER;'

EXEC (@v_SQL_1)


SET @v_SQL_2='
INSERT INTO ABST_ID'+@ENTITY+'.ABST_INSURANCE_CONTRACT_GROUP_MASTER
(
	ENTITY_ID,
	INSURANCE_CONTRACT_GROUP_ID,
	PORTFOLIO_GROUP,
	COHORT_YEAR,
	SET_OF_CONTRACT,
	PROFITABILITY_GROUP_PRICING,
	CCY_CD,
	MEASUREMENT_MODEL,
	NATURE,
	OCI_OPTION,
	L1,
	BATCH_DT,
	BATCH_RUN_ID,
	JOB_RUN_ID
)
SELECT
	ENTITY_ID,
	INSURANCE_CONTRACT_GROUP_ID,
	PORTFOLIO_GROUP,
	COHORT_YEAR,
	SET_OF_CONTRACT,
	PROFITABILITY_GROUP_PRICING,
	CCY_CD,
	MEASUREMENT_MODEL,
	NATURE,
	OCI_OPTION,
	L1,
	BATCH_DT,
	'+@BATCH_RUN_ID+',
	'+@JOB_RUN_ID+'
FROM (
		SELECT '''+@ENTITY+''' AS ENTITY_ID,
			INSURANCE_CONTRACT_GROUP_ID,
			PORTFOLIO_GROUP,
			COHORT_YEAR,
			SET_OF_CONTRACT,
			PROFITABILITY_GROUP_PRICING,
			CCY_CD,
			MEASUREMENT_MODEL,
			NATURE,
			OCI_OPTION,
			L1,
			BATCH_DT
		FROM (
		SELECT CASE 
			WHEN INSURANCE_CONTRACT_GROUP_MASTER.INSURANCE_CONTRACT_GROUP_ID LIKE ''%CON%'' THEN ''IAC'' 
			WHEN INSURANCE_CONTRACT_GROUP_MASTER.INSURANCE_CONTRACT_GROUP_ID LIKE ''%SHA%'' THEN ''IAS''
			WHEN INSURANCE_CONTRACT_GROUP_MASTER.INSURANCE_CONTRACT_GROUP_ID LIKE ''%B71%'' THEN ''IAS''
			ELSE ''ERROR'' 
		END FLAG, INSURANCE_CONTRACT_GROUP_MASTER.* FROM ABST_ID.ABST_INSURANCE_CONTRACT_GROUP_MASTER INSURANCE_CONTRACT_GROUP_MASTER
		) A
		WHERE FLAG='''+@ENTITY+'''
) ABST_INSURANCE_CONTRACT_GROUP_MASTER'

EXEC (@v_SQL_2)
