CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;

TRUNCATE TABLE FOND_ID.FOND_IFRS17_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER;

INSERT INTO FOND_ID.FOND_IFRS17_BENEFIT_INSURANCE_CONTRACT_GROUP_MASTER 
SELECT
   ICG_STORES.ENTITY_ID
 , ICG_STORES.POLICY_NO
 , ICG_STORES.PRODUCT_CD
 , ICG_STORES.BENEFIT_CD
 , ICG_STORES.COHORT_YEAR
 , ICG_STORES.ENTRY_MONTH
 , ICG_STORES.INSURANCE_CONTRACT_GROUP_ID
 , ICG_CONFIG.SUB_GROUP_ID
 , ICG_STORES.CB_START_DT
 , ICG_STORES.CB_END_DT
 , ICG_STORES.CCY_CD
 , @BATCH_MASTER_ID AS BATCH_MASTER_ID 
 , @BATCH_RUN_ID AS BATCH_RUN_ID 
 , @JOB_MASTER_ID AS JOB_MASTER_ID
 , @JOB_RUN_ID AS JOB_RUN_ID  
 , @BATCHDATESTR AS BATCHDATE
 , @GMT_START_DTTM AS ETL_PROCESS_DATE_TIME 

FROM
  ( 
	   SELECT
	     X.ENTITY_ID
	   , X.POLICY_NO
	   , X.PRODUCT_CD
	   , X.BENEFIT_CD
	   , X.CONTRACT_ID
	   , X.PORTFOLIO_GROUP
	   , X.COHORT_YEAR
	   , X.SET_OF_CONTRACT
	   , X.INSURANCE_CONTRACT_GROUP_ID
	   , X.ICG_ID_PROPHET
	   , X.ENTRY_MONTH
	   , X.CB_START_DT
	   , X.CB_END_DT
	   , X.MEASUREMENT_MODEL
	   , X.INFORCE_FLAG
	   , X.COVERAGE_LEVEL_END_DATE
	   , X.CCY_CD
	   , X.STATUS_SOURCE
	   , X.BEN_EXP_DATE
	   , X.SUBSYSTEM
	   , X.CREATED_DATE
	   , X.UPDATED_DATE
	   , ROW_NUMBER() OVER(PARTITION BY X.POLICY_NO, X.BENEFIT_CD ORDER BY X.CB_START_DT DESC, X.CB_END_DT DESC) AS IDX

       FROM FOND_ID.FOND_IFRS17_ICG_STORES X
  ) ICG_STORES

LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_ICG_CONFIG AS ICG_CONFIG 
ON ICG_STORES.PORTFOLIO_GROUP = ICG_CONFIG.PORTFOLIO_GROUP
AND ICG_STORES.COHORT_YEAR = ICG_CONFIG.COHORT_YEAR 
AND ICG_STORES.SET_OF_CONTRACT = ICG_CONFIG.SET_OF_CONTRACT
AND ICG_STORES.MEASUREMENT_MODEL = ICG_CONFIG.MEASUREMENT_MODEL
  
WHERE ICG_STORES.IDX = 1
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @JOB_RUN_ID AND BATCH_RUN_ID = @BATCH_RUN_ID;


