CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_PRODUCT_CONFIG] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;

TRUNCATE TABLE FOND_ID.FOND_IFRS17_PRODUCT_CONFIG;

INSERT INTO FOND_ID.FOND_IFRS17_PRODUCT_CONFIG
SELECT DISTINCT
   'IAI' AS ENTITY_ID
 , icg_stores.PRODUCT_CD
 , icg_stores.BENEFIT_CD
 , pfm.SERVICE_FLG
 , @BATCH_MASTER_ID AS BATCH_MASTER_ID 
 , @BATCH_RUN_ID AS BATCH_RUN_ID 
 , @JOB_MASTER_ID AS JOB_MASTER_ID
 , @JOB_RUN_ID AS JOB_RUN_ID  
 , @BATCHDATESTR AS BATCHDATE
 , @GMT_START_DTTM AS ETL_PROCESS_DATE_TIME 

FROM
  (
    SELECT
	  PRODUCT_CD
	, BENEFIT_CD
    
	FROM FOND_ID.FOND_IFRS17_ICG_STORES
    
	GROUP BY PRODUCT_CD, BENEFIT_CD
  ) icg_stores

LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_PORTFOLIO_MAPPING AS pfm
ON TRIM(icg_stores.PRODUCT_CD) = TRIM(pfm.PRODUCT_CD)
;

SELECT * FROM AUDIT_ID.ETL_AUDIT_JOB_RUN_DETAILS WHERE JOB_RUN_ID = @JOB_RUN_ID AND BATCH_RUN_ID = @BATCH_RUN_ID;


