CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_PRODUCT_CONFIG_ENTITY] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@ENTITY [NVARCHAR](2000),@P_PRD_ID [integer] AS

--- ABC Framework parameter
DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();
DECLARE @v_SQL_1 NVARCHAR(MAX);
DECLARE @v_SQL_2 NVARCHAR(MAX);

---------------------------------------------------
--- Setup ABC Framework Parameters
---------------------------------------------------
EXEC STAG_ID.USP_GetRunIdReturn_ENTITY
@JobName = @JOBNAMESTR
,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT
,@ENTITY = @ENTITY;

SET @v_SQL_1='TRUNCATE TABLE ABST_ID'+@ENTITY+'.ABST_PRODUCT_CONFIG;'

EXEC (@v_SQL_1)

SET @v_SQL_2='
INSERT INTO ABST_ID'+@ENTITY+'.ABST_PRODUCT_CONFIG
(
	ENTITY_ID,
	PRODUCT_CD,
	BENEFIT_CD,
	SERVICE_FLG,
	BATCH_DT,
	BATCH_RUN_ID,
	JOB_RUN_ID
)
SELECT
	ENTITY_ID,
	PRODUCT_CD,
	BENEFIT_CD,
	SERVICE_FLG,
	BATCH_DT,
	'+@BATCH_RUN_ID+',
	'+@JOB_RUN_ID+'
FROM (
		SELECT '''+@ENTITY+''' AS ENTITY_ID,
			PRODUCT_CD,
			BENEFIT_CD,
			SERVICE_FLG,
			BATCH_DT
			FROM (
				SELECT CASE 
						WHEN ICG_CONFIG.INSURANCE_CONTRACT_GROUP_ID LIKE ''%CON%'' THEN ''IAC'' 
						WHEN ICG_CONFIG.INSURANCE_CONTRACT_GROUP_ID LIKE ''%SHA%'' THEN ''IAS''
						WHEN ICG_CONFIG.INSURANCE_CONTRACT_GROUP_ID LIKE ''%B71%'' THEN ''IAS''
						ELSE ''ERROR'' END FLAG, PC.* FROM ABST_ID.ABST_PRODUCT_CONFIG PC 
						LEFT JOIN (SELECT PRODUCT_CD, SET_OF_CONTRACT FROM ( SELECT ROW_NUMBER() OVER (PARTITION BY PRODUCT_CD ORDER BY SET_OF_CONTRACT) AS RN, * FROM [STAG_ID].[STAG_CONFIG_IFRS17_SET_OF_CONTRACT] ) A WHERE RN=1) SOC ON SOC.PRODUCT_CD=PC.PRODUCT_CD
						LEFT JOIN (SELECT SET_OF_CONTRACT, INSURANCE_CONTRACT_GROUP_ID FROM ( SELECT ROW_NUMBER() OVER (PARTITION BY SET_OF_CONTRACT ORDER BY COHORT_YEAR DESC) AS RN, * FROM [STAG_ID].[STAG_CONFIG_IFRS17_ICG_CONFIG]	) A WHERE RN=1) ICG_CONFIG ON ICG_CONFIG.SET_OF_CONTRACT=SOC.SET_OF_CONTRACT
			) A 
		WHERE FLAG='''+@ENTITY+'''
) ABST_PRODUCT_CONFIG'

EXEC (@v_SQL_2)
