CREATE PROC [FOND_ID].[USP_LOAD_ETL1_IFRS17_FNC_MONTHLY_ICG_MPFILES_RESVPIA] @BATCHDATESTR [NVARCHAR](10),@JOBNAMESTR [NVARCHAR](2000),@P_PRD_ID [integer] AS
BEGIN
	DECLARE @V_START		datetime;
	DECLARE @V_END			datetime;
	DECLARE @V_DURATION		datetime;
	DECLARE @V_FUNCTION_NAME	NVARCHAR(2000) = 'USP_LOAD_ETL1_IFRS17_FNC_MONTHLY_ICG_MPFILES_RESVPIA';
	DECLARE @V_DESCRIPTION	NVARCHAR(2000);
	DECLARE @V_CMD			NVARCHAR(2000);
	DECLARE @V_SEQNO			integer = 0;
	DECLARE @V_PRD_ID		integer;
	DECLARE @V_CREATED_DATE	datetime;
	DECLARE @V_START_DATE	date;
	DECLARE @V_END_DATE		date;

	--- ABC Framework parameter
	DECLARE @BATCH_MASTER_ID    VARCHAR(20) = 0;
	DECLARE @BATCH_RUN_ID    VARCHAR(20)  = 0;
	DECLARE @JOB_MASTER_ID    VARCHAR(20)  = 0;
	DECLARE @JOB_RUN_ID    VARCHAR(20)  = 0;
	DECLARE @GMT_START_DTTM    VARCHAR(20) = getdate();
	
	BEGIN TRY
		SET @V_START_DATE	= convert(date, cast(@P_PRD_ID as varchar(8))); -- valuation extract date
		PRINT	'Start date :' + convert(varchar,@V_START_DATE,112);
		SET @V_START 	= convert(datetime,getDATE());

		SET @V_DESCRIPTION 	= 'Start ' + @V_FUNCTION_NAME + ' : ' + convert(varchar,@V_START,121);
		PRINT	@V_DESCRIPTION;
		SET @V_SEQNO		= @V_SEQNO + 1;

		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		---------------------------------------------------
		--- Setup ABC Framework Parameters
		---------------------------------------------------
		EXEC STAG_ID.USP_GetRunIdReturn
		@JobName = @JOBNAMESTR
		,@BATCH_MASTER_ID  = @BATCH_MASTER_ID OUTPUT
		,@BATCH_RUN_ID   = @BATCH_RUN_ID OUTPUT
		,@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT
		,@JOB_RUN_ID  = @JOB_RUN_ID OUTPUT
		,@GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;
		------END GET RUN ID DETAIL FROM ABC------
		
		---------------------------------------------------
		--- Drop Temporary Tables
		---------------------------------------------------
		IF OBJECT_ID('STAG_ID.TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY ') IS NOT NULL DROP TABLE STAG_ID.TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY;
		IF OBJECT_ID('FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_DUP ') IS NOT NULL DROP TABLE FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_DUP ;
		IF OBJECT_ID('STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA_ICG_FLAG') IS NOT NULL DROP TABLE STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA_ICG_FLAG;
		IF OBJECT_ID('STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA') IS NOT NULL DROP TABLE STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA;
		IF OBJECT_ID('tempdb.dbo.#TMP_IFRS17_ICG_STORES_RESVPIA_TMP_1', 'U') IS NOT NULL DROP TABLE tempdb.dbo.#TMP_IFRS17_ICG_STORES_RESVPIA_TMP_1;
		--IF OBJECT_ID('FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID') IS NOT NULL DROP TABLE FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID;
		--IF OBJECT_ID('FOND_ID.FOND_IFRS17_MPFILES_RESVPIA') IS NOT NULL DROP TABLE FOND_ID.FOND_IFRS17_MPFILES_RESVPIA;
		TRUNCATE TABLE FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID;
		TRUNCATE TABLE FOND_ID.FOND_IFRS17_MPFILES_RESVPIA;
		

		---------------------------------------------------
		--- Create Temporary Table for ICG Stores
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'CREATE TABLE TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

	
		-- get benefit expiry
		--drop table if exists STAG_ID.TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY ;
		
		CREATE TABLE STAG_ID.TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY  
		WITH
		(
		 DISTRIBUTION = HASH(POLICY_NO)
		 ,CLUSTERED COLUMNSTORE INDEX
		)
		as
		select covrpf.CHDRNUM as POLICY_NO, 
		CONVERT(date, cast(RISK_CESS_DATE as varchar(8))) as BEN_EXP_DATE
		,ipsupf.CRTABLE
		,row_number() over(partition by covrpf.CHDRNUM,ipsupf.CRTABLE order by  CONVERT(date, cast(RISK_CESS_DATE as varchar(8))) desc) as idx
		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		from STAG_ID.STAG_LIFEASIA_COVRPF covrpf
		join STAG_ID.STAG_LIFEASIA_IPSUPF ipsupf
		on covrpf.CHDRNUM = ipsupf.CHDRNUM 
		and trim(covrpf.CRTABLE) = trim(ipsupf.CRTABLE) 
		where covrpf.VALIDFLAG = 1
		;

		
		---------------------------------------------------
		--- Check Duplicate records
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'CREATE  TABLE TMP_IFRS17_ICG_STORES_RESVPIA_DUP  : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	

		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

	
		-- check duplicate
		--drop table if exists FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_DUP ;
		
		CREATE TABLE FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_DUP  
		WITH
		(
		 DISTRIBUTION = HASH(CHDRNUM)
		 ,CLUSTERED INDEX(CHDRNUM)
		)
		as
		select 
		-- existing column from ipsupf_v2
		NULLIF(TRIM(ipsupf.CHDRNUM),'') AS CHDRNUM,
		ipsupf.CRTABLE,
		ipsupf.ANBCCD,
		ipsupf.SEX,
		ipsupf.PCESSTRM,
		ipsupf.INSTOT,
		ipsupf.SUMINS,
		ipsupf.MORTCLS,
		ipsupf.HOISSDTE,
		ipsupf.CRRCD,
		ipsupf.TOPUPAMNT,
		ipsupf.WDRAMNT,
		ipsupf.TTLFUND,
		ipsupf.PRCF,
		ipsupf.PREF,
		ipsupf.PRFF,
		ipsupf.PRMF,
		ipsupf.PDMF,
		ipsupf.STATCODE,
		ipsupf.SLSCNL,
		ipsupf.CHGDTE,
		ipsupf.CURYRTUP,
		ipsupf.TOPUPLAST,
		ipsupf.BILCHNL,
		ipsupf.CLNTCODE,
		ipsupf.CLTPHONE01,
		ipsupf.CLTPHONE02,
		ipsupf.LIFCNUM,
		ipsupf.AGNTNUM,
		ipsupf.AGTNAME,
		ipsupf.DTEAPP,
		ipsupf.DTETRM,
		ipsupf.TSALESUNT,
		ipsupf.UNITNUM,
		ipsupf.UNITNAME,
		ipsupf.REGION,
		ipsupf.PRMP,
		ipsupf.PRODCAT,
		ipsupf.TPDCLAIM,
		ipsupf.ADDR04CITY,
		ipsupf.ADDR05PROV,
		ipsupf.SPEF,
		ipsupf.SPMF,
		ipsupf.SPFF,
		ipsupf.SPCF,
		ipsupf.SPMP,
		ipsupf.SPDF,
		ipsupf.SPTTLAMNT,
		ipsupf.TOPUPEF,
		ipsupf.TOPUPMF,
		ipsupf.TOPUPFF,
		ipsupf.TOPUPCF,
		ipsupf.TOPUPMP,
		ipsupf.TOPUPDF,
		ipsupf.TTTLTOPUP,
		ipsupf.WITHEF,
		ipsupf.WITHMF,
		ipsupf.WITHFF,
		ipsupf.WITHCF,
		ipsupf.WITHMP,
		ipsupf.WITHDF,
		ipsupf.TTLWITHAMT,
		ipsupf.LOADINGEXT,
		ipsupf.CLTDOB,
		ipsupf.MEDPRVIND,
		ipsupf.CNTCURR,
		ipsupf.ZZSRCE,
		ipsupf.UALPCTA,
		ipsupf.UALPCTB,
		ipsupf.UALPCTC,
		ipsupf.UALPCTD,
		ipsupf.UALPCTE,
		ipsupf.UALPCTF,
		ipsupf.CODE,
		ipsupf.ZLONGDESC,
		ipsupf.ACTVALUE,
		ipsupf.SURRDATE,
		ipsupf.LSTWDWDATE,
		ipsupf.LSTTOPDATE,
		ipsupf.PRGC,
		ipsupf.PDGC,
		ipsupf.SPRGC,
		ipsupf.SPDGC,
		ipsupf.TOPUPRGC,
		ipsupf.TOPUPGDC,
		ipsupf.WITHRGC,
		ipsupf.WITHDGC,
		ipsupf.UALPCTG,
		ipsupf.UALPCTH,
		ipsupf.PREP,
		ipsupf.SPEP,
		ipsupf.TOPUPEP,
		ipsupf.WITHEP,
		ipsupf.UALPCTI,
		ipsupf.PRIEF,
		ipsupf.SPRIEF,
		ipsupf.TUPRIEF,
		ipsupf.WDPRIEF,
		ipsupf.PRIEFPCT,
		ipsupf.REGIONFLG,
		ipsupf.PRVEF,
		ipsupf.SPRVEF,
		ipsupf.TUPRVEF,
		ipsupf.WDPRVEF,
		ipsupf.PRVEFPCT,
		ipsupf.PRAEF,
		ipsupf.SPRAEF,
		ipsupf.TUPRAEF,
		ipsupf.WDPRAEF,
		ipsupf.PRAEFPCT,
		ipsupf.PDIEF,
		ipsupf.LBIND,
		ipsupf.BASPRCF,
		ipsupf.BASPREF,
		ipsupf.BASPRFF,
		ipsupf.BASPRMF,
		ipsupf.BASPDMF,
		ipsupf.BASPRMPF,
		ipsupf.BASPRGCEF,
		ipsupf.BASPDGCEF,
		ipsupf.BASPREPF,
		ipsupf.BASPRIE,
		ipsupf.BASPRVE,
		ipsupf.BASPRAE,
		ipsupf.TOPPRCF,
		ipsupf.TOPPREF,
		ipsupf.TOPPRFF,
		ipsupf.TOPPRMF,
		ipsupf.TOPPDMF,
		ipsupf.TOPPRMPF,
		ipsupf.TOPPRGCEF,
		ipsupf.TOPPDGCEF,
		ipsupf.TOPPREPF,
		ipsupf.TOPPRIE,
		ipsupf.TOPPRVE,
		ipsupf.TOPPRAE,
		ipsupf.TOTBASFUND,
		ipsupf.TOTTOPFUND,
		ipsupf.PDGV,
		ipsupf.PDGM,
		ipsupf.PRGV,
		ipsupf.PRGM,
		ipsupf.PREC,
		ipsupf.PSEC,
		ipsupf.PDMM,
		ipsupf.PDIF,
		ipsupf.PDNV,
		ipsupf.SPMM,
		ipsupf.SPIF,
		ipsupf.SPNV,
		ipsupf.TOPUPMM,
		ipsupf.TOPUPIF,
		ipsupf.TOPUPNV,
		ipsupf.WITHMM,
		ipsupf.WITHIF,
		ipsupf.WITHNV,
		ipsupf.UALPCTJ,
		ipsupf.UALPCTK,
		ipsupf.UALPCTL,
		ipsupf.BASPDMM,
		ipsupf.BASPDIF,
		ipsupf.BASPDNV,
		ipsupf.TOPPDMM,
		ipsupf.TOPPDIF,
		ipsupf.TOPPDNV,
		ipsupf.PDFI,
		ipsupf.SPFI,
		ipsupf.TOPUPFI,
		ipsupf.WITHFI,
		ipsupf.UALPCTM,
		ipsupf.BASPDFI,
		ipsupf.TOPPDFI,
		ipsupf.PRNV,
		ipsupf.SPPR,
		ipsupf.TOPUPPR,
		ipsupf.WITHPR,
		ipsupf.UALPCTN,
		ipsupf.BASPDPR,
		ipsupf.TOPPDPR,
		ipsupf.PDGT,
		ipsupf.SPGT,
		ipsupf.TOPUPGT,
		ipsupf.WITHGT,
		ipsupf.UALPCTO,
		ipsupf.BASPDGT,
		ipsupf.TOPPDGT,
		ipsupf.STAT_SECT,
		ipsupf.PRMI,
		ipsupf.SRMI,
		ipsupf.TOPUPRI,
		ipsupf.WITHRI,
		ipsupf.UALPCTP,
		ipsupf.BASPRMI,
		ipsupf.TOPPRMI,
		ipsupf.PDMI,
		ipsupf.SDMI,
		ipsupf.TOPUPDI,
		ipsupf.WITHDI,
		ipsupf.UALPCTQ,
		ipsupf.BASPDMI,
		ipsupf.TOPPDMI,
		ipsupf.FLAGS,
		ipsupf.PRDP,
	    ipsupf.SP_PRDP,
	    ipsupf.TU_PRDP,
	    ipsupf.WITH_PRDP,
	    ipsupf.PERC_PRDP,
	    ipsupf.BAS_PRDP,
	    ipsupf.TOP_PRDP

		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		from STAG_ID.STAG_LIFEASIA_IPSUPF ipsupf
		where CHDRNUM in (select CHDRNUM from STAG_ID.STAG_LIFEASIA_IPSUPF 
		where NULLIF(TRIM(CHDRNUM),'') IS NOT NULL group by CHDRNUM having count(*) > 1)
		;  


		---------------------------------------------------
		--- Create Temporary Table for ICG Identification Process
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'CREATE TABLE TMP_IFRS17_ICG_STORES_RESVPIA_ICG_FLAG : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	


		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

	
		--drop table if exists STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA_icg_flag;
		
		CREATE TABLE STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA_ICG_FLAG 
		WITH
		(
		 DISTRIBUTION = HASH(POLICY_NO)
		 ,CLUSTERED INDEX (POLICY_NO)
		)
		AS 
		SELECT distinct (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) AS POLICY_NO
		,(CASE WHEN UPPER(TRIM(A.STATCODE)) = 'IF' THEN   
				(CASE WHEN ICGS.POLICY_NO IS NULL THEN 'NEW BUSINESS'
					   WHEN CBM.BOUND_BY_REPRICE='N' AND CBM.BOUND_BY_TERMINATION_PROVISION = 'N' AND ICGS.STATUS_SOURCE <> 'IF' THEN 'UPDATE EXISTING BUSINESS'
					   WHEN CBM.BOUND_BY_REPRICE='N' AND CBM.BOUND_BY_TERMINATION_PROVISION = 'N' THEN 'NO UPDATE'
					   WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN 'NEW BUSINESS' 
					   WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN 'NEW BUSINESS'
					   WHEN ICGS.STATUS_SOURCE <> 'IF' THEN 'UPDATE EXISTING BUSINESS'
					   ELSE 'NO UPDATE'
				END)
			   -- A.STATCODE <> 'IF'
			   WHEN ICGS.POLICY_NO IS NULL THEN 'NEW BUSINESS'
			   WHEN A.STATCODE IS NULL THEN 'UPDATE EXISTING BUSINESS'
			   WHEN LOWER(TRIM(A.STATCODE)) <> LOWER(TRIM(ICGS.STATUS_SOURCE)) THEN 'UPDATE EXISTING BUSINESS'
			   ELSE 'NO UPDATE'
		END) AS ICG_FLAG
		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		FROM STAG_ID.STAG_LIFEASIA_IPSUPF A
		LEFT JOIN FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_DUP dup 
		on (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = dup.CHDRNUM
		LEFT JOIN (
			select a.*
			, row_number() over(partition by POLICY_NO 
			order by CB_START_DT desc, CB_END_DT desc, CREATED_DATE desc, UPDATED_DATE desc) as idx 
			FROM FOND_ID.FOND_IFRS17_ICG_STORES a
			where lower(trim(SUBSYSTEM)) = lower(trim('Resvpia'))
			AND PRODUCT_CD = BENEFIT_CD
		) ICGS
		on (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = ICGS.POLICY_NO AND ICGS.idx = 1
		LEFT JOIN STAG_ID.TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY BEXP on A.CHDRNUM = BEXP.POLICY_NO AND A.CRTABLE=BEXP.CRTABLE AND BEXP.idx=1
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_CB_MAPPING CBM ON A.CRTABLE = CBM.PRODUCT_CD
		AND UPPER(TRIM(CAST('Life Asia' AS VARCHAR(20)))) = UPPER(TRIM(CBM.SYSTEM))
		where dup.CHDRNUM is null
		;
	
		----------------------------------------------
		--create temp table tempdb.dbo.#TMP_IFRS17_ICG_STORES_RESVPIA_TMP_1
		-----------------------------------------------
		
		SET @V_SEQNO = @V_SEQNO + 1;
		SET @V_START = CURRENT_TIMESTAMP;
		SET @V_DESCRIPTION = CONCAT('create temp table tempdb.dbo.#TMP_IFRS17_ICG_STORES_RESVPIA_TMP_1 : ', @V_START);

		INSERT INTO STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE, FUNC_NAME, SEQNO, [DESCRIPTION])
		VALUES (@V_START, @V_FUNCTION_NAME, @V_SEQNO, @V_DESCRIPTION);

		CREATE TABLE tempdb.dbo.#TMP_IFRS17_ICG_STORES_RESVPIA_TMP_1
		WITH
		(
		  DISTRIBUTION = HASH(POLICY_NO),
		  HEAP
		)
		AS
		SELECT  
		-- icg_stores column
		CAST('IAI' AS VARCHAR(4)) AS ENTITY_ID
		,CAST('Life Asia' AS VARCHAR(20)) AS SYSTEM
		,NULLIF(TRIM(A.CHDRNUM),'') AS POLICY_NO
		--,A.CRTABLE AS PRODUCT_CD
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN A.CRTABLE
			 ELSE ICGS.PRODUCT_CD
		END) AS PRODUCT_CD
		--,A.CRTABLE AS BENEFIT_CD
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN A.CRTABLE
			 ELSE ICGS.BENEFIT_CD
		END) AS BENEFIT_CD
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN 
				NULLIF(TRIM(A.CHDRNUM),'') + '-' + FORMAT((CASE 	
					WHEN A.HOISSDTE = 99999999 THEN NULL
					WHEN A.HOISSDTE = 0 THEN NULL
					WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.HOISSDTE as integer) as varchar(8))) 
					WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
					WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
				END),'yyyy')
			   ELSE ICGS.CONTRACT_ID
		END) AS CONTRACT_ID
		,(CASE
		    WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			  CASE
	            WHEN PFM.PRODUCT_CD IS NOT NULL THEN
	              CASE
		            WHEN PFM.VFA_ELIGIBLE = 'N' THEN PFM.PORTFOLIO_GROUP
		             WHEN PFM.VFA_ELIGIBLE = 'Y' AND RIGHT(PFM.PORTFOLIO_GROUP,3) NOT IN ('VFA') THEN TRIM(PFM.PORTFOLIO_GROUP) + '_' +  
				      CASE
					    WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 0 THEN 'GMM'
						WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 1 THEN 'VFA'
					  END
			        WHEN PFM.VFA_ELIGIBLE = 'Y' THEN SUBSTRING(TRIM(PFM.PORTFOLIO_GROUP), 1, LEN(TRIM(PFM.PORTFOLIO_GROUP))-3) +
			          CASE
			            WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 0 THEN 'GMM'
				        WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 1 THEN 'VFA'
			          END
		          END
			  END
		    ELSE ICGS.PORTFOLIO_GROUP
		  END) AS PORTFOLIO_GROUP
		,CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			CAST(FORMAT((
				(CASE 	
					WHEN A.HOISSDTE = 99999999 THEN NULL
					WHEN A.HOISSDTE = 0 THEN NULL
					WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.HOISSDTE as integer) as varchar(8))) 
					WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
					WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
				END)
			 ),'yyyy') AS NUMERIC(4,0)) 
		 ELSE ICGS.COHORT_YEAR END as COHORT_YEAR
		--,SC.SET_OF_CONTRACT
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN SC.SET_OF_CONTRACT
			 ELSE ICGS.SET_OF_CONTRACT
		END) AS SET_OF_CONTRACT
		--,ICC.INSURANCE_CONTRACT_GROUP_ID
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN ICC.INSURANCE_CONTRACT_GROUP_ID
			 ELSE ICGS.INSURANCE_CONTRACT_GROUP_ID
		END) AS INSURANCE_CONTRACT_GROUP_ID
		--,ICC.ICG_ID_PROPHET
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN ICC.ICG_ID_PROPHET
			 ELSE ICGS.ICG_ID_PROPHET
		END) AS ICG_ID_PROPHET
		,CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			CAST(FORMAT((
				(CASE 	
					WHEN A.HOISSDTE = 99999999 THEN NULL
					WHEN A.HOISSDTE = 0 THEN NULL
					WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.HOISSDTE as integer) as varchar(8))) 
					WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
					WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
				END)
			),'MM') AS NUMERIC(2,0)) ELSE ICGS.ENTRY_MONTH
		END AS ENTRY_MONTH
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN
				(CASE 	
					WHEN A.HOISSDTE = 99999999 THEN NULL
					WHEN A.HOISSDTE = 0 THEN NULL
					WHEN ICGS.POLICY_NO IS NULL AND A.CRRCD > A.HOISSDTE  THEN CONVERT(date, cast(cast(A.HOISSDTE as integer) as varchar(8))) 
					WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.CRRCD as integer) as varchar(8))) 
					WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
					WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
				END)
			 ELSE ICGS.CB_START_DT
		END) AS CB_START_DT
		
		,(CASE
		    WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			  CASE
	            WHEN PFM.PRODUCT_CD IS NOT NULL THEN
	              CASE
		            WHEN PFM.VFA_ELIGIBLE = 'N' THEN PFM.MEASUREMENT_MODEL
			        WHEN PFM.VFA_ELIGIBLE = 'Y' THEN
			          CASE
			            WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 0 THEN 'GMM'
				        WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 1 THEN 'VFA'
			          END
		          END
			  END
		    ELSE ICGS.MEASUREMENT_MODEL
		  END) AS MEASUREMENT_MODEL
		--,SMT.INFORCE_FLAG
		,(CASE WHEN ICG_FLAG IN ('NEW BUSINESS','UPDATE EXISTING BUSINESS') THEN SMT.INFORCE_FLAG
			 ELSE ICGS.INFORCE_FLAG
		END) AS INFORCE_FLAG
		-- need confirmation and will be updated in the next iteration
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			(CASE 
				WHEN BOUND_BY_REPRICE='N' AND BOUND_BY_TERMINATION_PROVISION = 'N' THEN BEXP.BEN_EXP_DATE -- BEN_EXP_DATE (RISK_CESS_DATE) 
				WHEN BOUND_BY_REPRICE = 'Y' AND BOUND_BY_TERMINATION_PROVISION = 'N' THEN 
					 dateadd(month,COALESCE(CAST(CBM.POINT_OF_BOUNDARY_REPRICE AS integer),0),
						(CASE 	
							WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.CRRCD as integer) as varchar(8))) 
							WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
							WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
						END))
				WHEN BOUND_BY_TERMINATION_PROVISION = 'Y' AND BOUND_BY_REPRICE = 'N'  THEN 
					 dateadd(month,COALESCE(CAST(CBM.POINT_OF_BOUNDARY_TERMINATION AS integer),0),
						 (CASE 	
							WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.CRRCD as integer) as varchar(8))) 
							WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
							WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
						 END))
			END)
			 ELSE ICGS.CB_END_DT
		END) AS COVERAGE_LEVEL_END_DATE
		--,A.CNTCURR AS CCY_CD
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN A.CNTCURR
			   ELSE ICGS.CCY_CD
		END) AS CCY_CD
		--,A.STATCODE AS STATUS_SOURCE
		,(CASE WHEN ICG_FLAG IN ('NEW BUSINESS','UPDATE EXISTING BUSINESS') THEN A.STATCODE
			   ELSE ICGS.STATUS_SOURCE
		END) AS STATUS_SOURCE
		--,BEXP.BEN_EXP_DATE 
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN BEXP.BEN_EXP_DATE
				 ELSE ICGS.BEN_EXP_DATE
		END) AS BEN_EXP_DATE
		,ICG_FLAG
		,cast('Resvpia' as varchar(20)) as SUBSYSTEM
		--,CURRENT_TIMESTAMP as CREATED_DATE
		--,CURRENT_TIMESTAMP as UPDATED_DATE
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN CURRENT_TIMESTAMP
				 ELSE ICGS.CREATED_DATE
		END) AS CREATED_DATE
		,(CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN CURRENT_TIMESTAMP
				 ELSE ICGS.UPDATED_DATE
		END) AS UPDATED_DATE
		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		FROM STAG_ID.STAG_LIFEASIA_IPSUPF A
		LEFT JOIN FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_DUP  dup 
		on (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = dup.CHDRNUM
		LEFT JOIN STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA_ICG_FLAG icg_flag 
		on (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = icg_flag.POLICY_NO
		LEFT JOIN (
			select a.*
			, row_number() over(partition by POLICY_NO 
			order by CB_START_DT desc, CB_END_DT desc, CREATED_DATE desc, UPDATED_DATE desc) as idx 
			FROM FOND_ID.FOND_IFRS17_ICG_STORES a
			where lower(trim(SUBSYSTEM)) = lower(trim('Resvpia'))
			AND PRODUCT_CD = BENEFIT_CD
		) ICGS
		on (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = ICGS.POLICY_NO AND ICGS.idx = 1
		LEFT JOIN STAG_ID.TMP_IFRS17_RESVPIA_BENEFIT_EXPIRY  BEXP 
		on (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = BEXP.POLICY_NO AND A.CRTABLE=BEXP.CRTABLE AND BEXP.idx=1
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_VFA_ELIGIBILITY AS VFA_ELIGIBILITY
        ON (CASE WHEN NULLIF(TRIM(A.CHDRNUM),'') IS NOT NULL THEN A.CHDRNUM ELSE 'N/A' END) = VFA_ELIGIBILITY.POLICY_NO
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_CB_MAPPING CBM ON A.CRTABLE = CBM.PRODUCT_CD
		AND UPPER(TRIM(CAST('Life Asia' AS VARCHAR(20)))) = UPPER(TRIM(CBM.SYSTEM))
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_PORTFOLIO_MAPPING PFM
		on A.CRTABLE = PFM.PRODUCT_CD AND A.CNTCURR = PFM.CCY_CD 
		AND UPPER(TRIM(CAST('Life Asia' AS VARCHAR(20)))) = UPPER(TRIM(PFM.SYSTEM))
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_SET_OF_CONTRACT SC
		ON A.CRTABLE = SC.PRODUCT_CD AND A.CNTCURR = SC.CCY_CD
		AND UPPER(TRIM(CAST('Life Asia' AS VARCHAR(20)))) = UPPER(TRIM(SC.SYSTEM))
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_ICG_CONFIG ICC
		ON (CASE
		    WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			  CASE
	            WHEN PFM.PRODUCT_CD IS NOT NULL THEN
	              CASE
		            WHEN PFM.VFA_ELIGIBLE = 'N' THEN PFM.PORTFOLIO_GROUP
		             WHEN PFM.VFA_ELIGIBLE = 'Y' AND RIGHT(PFM.PORTFOLIO_GROUP,3) NOT IN ('VFA') THEN TRIM(PFM.PORTFOLIO_GROUP) + '_' +  
				      CASE
					    WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 0 THEN 'GMM'
						WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 1 THEN 'VFA'
					  END
			        WHEN PFM.VFA_ELIGIBLE = 'Y' THEN SUBSTRING(TRIM(PFM.PORTFOLIO_GROUP), 1, LEN(TRIM(PFM.PORTFOLIO_GROUP))-3) +
			          CASE
			            WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 0 THEN 'GMM'
				        WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 1 THEN 'VFA'
			          END
		          END
			  END
		    ELSE ICGS.PORTFOLIO_GROUP
		  END) = TRIM(ICC.PORTFOLIO_GROUP)
		AND (CASE
		    WHEN ICG_FLAG = 'NEW BUSINESS' THEN
			  CASE
	            WHEN PFM.PRODUCT_CD IS NOT NULL THEN
	              CASE
		            WHEN PFM.VFA_ELIGIBLE = 'N' THEN PFM.MEASUREMENT_MODEL
			        WHEN PFM.VFA_ELIGIBLE = 'Y' THEN
			          CASE
			            WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 0 THEN 'GMM'
				        WHEN VFA_ELIGIBILITY.POLICY_NO IS NOT NULL AND VFA_ELIGIBILITY.IFRS_MEASURE_MODEL = 1 THEN 'VFA'
			          END
		          END
			  END
		    ELSE ICGS.MEASUREMENT_MODEL
		  END) = TRIM(ICC.MEASUREMENT_MODEL)
		AND CAST(FORMAT((CASE WHEN ICG_FLAG = 'NEW BUSINESS' THEN
				(CASE 	
						WHEN A.HOISSDTE = 99999999 THEN NULL
						WHEN A.HOISSDTE = 0 THEN NULL
						WHEN ICGS.POLICY_NO IS NULL THEN CONVERT(date, cast(cast(A.HOISSDTE as integer) as varchar(8))) 
						WHEN CBM.BOUND_BY_REPRICE = 'Y' AND dateadd(day,-1,BEXP.BEN_EXP_DATE) >  ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
						WHEN CBM.BOUND_BY_TERMINATION_PROVISION = 'Y' AND @V_START_DATE > ICGS.CB_END_DT THEN dateadd(day,1,ICGS.CB_END_DT)
				END)
			 ELSE ICGS.CB_START_DT
		END),'yyyy') AS NUMERIC(4,0)) = CAST(ICC.COHORT_YEAR AS NUMERIC(4,0))
		AND TRIM(SC.SET_OF_CONTRACT) = TRIM(ICC.SET_OF_CONTRACT)
		LEFT JOIN STAG_ID.STAG_CONFIG_IFRS17_STATUS_MAPPING_TABLE SMT on 
		(CASE WHEN ICG_FLAG IN ('NEW BUSINESS','UPDATE EXISTING BUSINESS') THEN A.STATCODE
			   ELSE ICGS.STATUS_SOURCE
		END) = SMT.STATUS_SOURCE
		AND UPPER(TRIM(CAST('Life Asia' AS VARCHAR(20)))) = UPPER(TRIM(SMT.SYSTEM))

		WHERE dup.CHDRNUM IS NULL
		;
		---------------------------------------------------
		--- Get ICG Stores only for non duplicate records
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'CREATE TABLE TMP_IFRS17_ICG_STORES_RESVPIA : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

	
	
		-- drop table
		--drop TABLE if exists STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA;
		
		CREATE TABLE STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA 
		WITH
		(
		 DISTRIBUTION = HASH(POLICY_NO)
		 ,CLUSTERED INDEX (POLICY_NO)
		)
		AS
		SELECT  
		ENTITY_ID
		,SYSTEM
		,POLICY_NO
		,PRODUCT_CD
		,BENEFIT_CD
		,CONTRACT_ID
		,PORTFOLIO_GROUP
		,COHORT_YEAR
		,SET_OF_CONTRACT
		,INSURANCE_CONTRACT_GROUP_ID
		,ICG_ID_PROPHET
		,ENTRY_MONTH
		,CB_START_DT
		,CASE 
			WHEN CB_START_DT > COVERAGE_LEVEL_END_DATE THEN CB_START_DT 
			ELSE COVERAGE_LEVEL_END_DATE 
		END AS CB_END_DT
		,MEASUREMENT_MODEL
		,INFORCE_FLAG
		,COVERAGE_LEVEL_END_DATE
		,CCY_CD
		,STATUS_SOURCE
		,BEN_EXP_DATE
		,ICG_FLAG
		,SUBSYSTEM
		,CREATED_DATE
		,UPDATED_DATE
		-- additional ABC Framework columns
		,BATCH_MASTER_ID 
		,BATCH_RUN_ID 
		,JOB_MASTER_ID
		,JOB_RUN_ID  
		,BATCHDATE
		,ETL_PROCESS_DATE_TIME 
		FROM tempdb.dbo.#TMP_IFRS17_ICG_STORES_RESVPIA_TMP_1
		;

		--------------------------------------------------------------------
		--- Create Report for invalid ICG Stores  IFRS17
		--- will be change after get final structure
		--------------------------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'CREATE VIEW  FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID: ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		--drop table if exists FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID;
		/*
		CREATE TABLE FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID 
		WITH
		(
		 DISTRIBUTION = HASH(POLICY_NO)
		 ,CLUSTERED COLUMNSTORE INDEX
		)
		as
		*/
		INSERT INTO FOND_ID.FOND_IFRS17_ICG_STORES_RESVPIA_INVALID
		select 
		a.ENTITY_ID
		,a.SYSTEM
		,a.POLICY_NO
		,a.PRODUCT_CD
		,a.BENEFIT_CD
		,a.CONTRACT_ID
		,a.PORTFOLIO_GROUP
		,a.COHORT_YEAR
		,a.SET_OF_CONTRACT
		,a.INSURANCE_CONTRACT_GROUP_ID
		,a.ICG_ID_PROPHET
		,a.ENTRY_MONTH
		,CB_START_DT as CB_START_DT
		,(case when a.CB_END_DT IS NOT NULL AND a.BEN_EXP_DATE IS NOT NULL THEN (case when a.CB_END_DT <= a.BEN_EXP_DATE then a.CB_END_DT else a.BEN_EXP_DATE end) ELSE NULL end) as CB_END_DT
		,MEASUREMENT_MODEL 
		,INFORCE_FLAG
		,(case when a.COVERAGE_LEVEL_END_DATE IS NOT NULL AND a.BEN_EXP_DATE IS NOT NULL THEN (case when a.COVERAGE_LEVEL_END_DATE <= a.BEN_EXP_DATE then a.COVERAGE_LEVEL_END_DATE else a.BEN_EXP_DATE end) ELSE NULL end) as COVERAGE_LEVEL_END_DATE
		,CCY_CD
		,STATUS_SOURCE
		,BEN_EXP_DATE as BEN_EXP_DATE
		,SUBSYSTEM
		,CREATED_DATE
		,UPDATED_DATE
		,upper(
			(case when NULLIF(TRIM(a.POLICY_NO),'') is null then 'POLICY_NO,' else '' end)+
			(case when NULLIF(TRIM(a.PRODUCT_CD),'') is null then 'PRODUCT_CD,' else '' end)+
			(case when NULLIF(TRIM(a.BENEFIT_CD),'') is null then 'BENEFIT_CD,' else '' end)+
			(case when NULLIF(TRIM(a.CONTRACT_ID),'') is null then 'CONTRACT_ID,' else '' end)+
			(case when NULLIF(TRIM(a.PORTFOLIO_GROUP),'') is null then 'PORTFOLIO_GROUP,' else '' end)+
			(case when a.COHORT_YEAR is null then 'COHORT_YEAR,' else '' end)+
			(case when NULLIF(TRIM(a.SET_OF_CONTRACT),'') is null then 'SET_OF_CONTRACT,' else '' end)+
			(case when NULLIF(TRIM(a.INSURANCE_CONTRACT_GROUP_ID),'') is null then 'INSURANCE_CONTRACT_GROUP_ID,' else '' end)+
			(case when a.ICG_ID_PROPHET is null then 'ICG_ID_PROPHET,' else '' end)+
			(case when a.ENTRY_MONTH is null then 'ENTRY_MONTH,' else '' end)+
			(case when a.CB_START_DT is null then 'CB_START_DT,' else '' end)+
			(case when (case when a.CB_END_DT IS NOT NULL AND a.BEN_EXP_DATE IS NOT NULL THEN (case when a.CB_END_DT <= a.BEN_EXP_DATE then a.CB_END_DT else a.BEN_EXP_DATE end) ELSE NULL end) is null then 'CB_END_DT,' else '' end)+
			(case when NULLIF(TRIM(a.MEASUREMENT_MODEL),'') is null then 'MEASUREMENT_MODEL,' else '' end)+
			(case when NULLIF(TRIM(a.INFORCE_FLAG),'') is null then 'INFORCE_FLAG,' else '' end)+
			(case when (case when a.COVERAGE_LEVEL_END_DATE IS NOT NULL AND a.BEN_EXP_DATE IS NOT NULL THEN (case when a.COVERAGE_LEVEL_END_DATE <= a.BEN_EXP_DATE then a.COVERAGE_LEVEL_END_DATE else a.BEN_EXP_DATE end) ELSE NULL end) is null then 'COVERAGE_LEVEL_END_DATE,' else '' end)+
			(case when NULLIF(TRIM(a.CCY_CD),'') is null then 'CCY_CD,' else '' end)+
			(case when NULLIF(TRIM(a.STATUS_SOURCE),'') is null then 'STATUS_SOURCE,' else '' end) +
			(case when a.BEN_EXP_DATE is null then 'BEN_EXP_DATE,' else '' end)+
			(case when a.CB_START_DT > a.BEN_EXP_DATE then 'CB_START_DT > BEN_EXP_DATE,' else '' end)
		) as INVALID_DESC 
		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		from STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA a
		where 
		(case 	
			when NULLIF(TRIM(POLICY_NO),'') is null then 'N'
			when NULLIF(TRIM(PRODUCT_CD),'') is null then 'N'
			when NULLIF(TRIM(BENEFIT_CD),'') is null then 'N'
			when NULLIF(TRIM(CONTRACT_ID),'') is null then 'N'
			when NULLIF(TRIM(PORTFOLIO_GROUP),'') is null then 'N'
			when COHORT_YEAR is null then 'N'
			when NULLIF(TRIM(SET_OF_CONTRACT),'') is null then 'N'
			when NULLIF(TRIM(INSURANCE_CONTRACT_GROUP_ID),'') is null then 'N'
			when ICG_ID_PROPHET is null then 'N'
			when ENTRY_MONTH is null then 'N'
			when CB_START_DT is null then 'N'
			when CB_END_DT is null then 'N'
			when NULLIF(TRIM(MEASUREMENT_MODEL),'') is null then 'N'
			when NULLIF(TRIM(INFORCE_FLAG),'') is null then 'N'
			when COVERAGE_LEVEL_END_DATE is null then 'N'
			when NULLIF(TRIM(CCY_CD),'') is null then 'N'
			when NULLIF(TRIM(STATUS_SOURCE),'') is null then 'N'
			when BEN_EXP_DATE is null then 'N'
			when (CB_START_DT > BEN_EXP_DATE AND STATUS_SOURCE = 'IF') then 'N'
			ELSE 'Y'
		end) = 'N'
		; 


		---------------------------------------------------
		--- Begin transaction
		---------------------------------------------------
		--BEGIN TRAN;
		--SET NOCOUNT ON
		
		---------------------------------------------------
		--- Update existing records to ICG Stores Tables for new business
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'update FOND_ID.FOND_IFRS17_ICG_STORES for new business : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		-- update existing records in icg stores for valid new business. update only INFORCE_FLAG='N'
		update FOND_ID.FOND_IFRS17_ICG_STORES 
		set INFORCE_FLAG = 'N', UPDATED_DATE=CURRENT_TIMESTAMP
		from STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA 
		where FOND_IFRS17_ICG_STORES.POLICY_NO = TMP_IFRS17_ICG_STORES_RESVPIA.POLICY_NO
		AND FOND_IFRS17_ICG_STORES.PRODUCT_CD = TMP_IFRS17_ICG_STORES_RESVPIA.PRODUCT_CD
		AND FOND_IFRS17_ICG_STORES.BENEFIT_CD = TMP_IFRS17_ICG_STORES_RESVPIA.BENEFIT_CD	
		AND TMP_IFRS17_ICG_STORES_RESVPIA.ICG_FLAG = 'NEW BUSINESS'
		AND lower(trim(FOND_IFRS17_ICG_STORES.SUBSYSTEM)) = lower(trim('Resvpia'))
		AND (case 	
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.POLICY_NO),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.PRODUCT_CD),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.BENEFIT_CD),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.CONTRACT_ID),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.PORTFOLIO_GROUP),'') is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.COHORT_YEAR is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.SET_OF_CONTRACT),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.INSURANCE_CONTRACT_GROUP_ID),'') is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.ICG_ID_PROPHET is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.ENTRY_MONTH is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.CB_START_DT is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.CB_END_DT is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.MEASUREMENT_MODEL),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.INFORCE_FLAG),'') is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.COVERAGE_LEVEL_END_DATE is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.CCY_CD),'') is null then 'N'
			when NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.STATUS_SOURCE),'') is null then 'N'
			when TMP_IFRS17_ICG_STORES_RESVPIA.BEN_EXP_DATE is null then 'N'
			when (TMP_IFRS17_ICG_STORES_RESVPIA.CB_START_DT > TMP_IFRS17_ICG_STORES_RESVPIA.BEN_EXP_DATE  AND TMP_IFRS17_ICG_STORES_RESVPIA.STATUS_SOURCE = 'IF')then 'N'
			ELSE 'Y'
		end) = 'Y'
		;

		---------------------------------------------------
		--- Update existing records to ICG Stores Tables
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'update FOND_ID.FOND_IFRS17_ICG_STORES: ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		-- update existing records in icg stores.
		update FOND_ID.FOND_IFRS17_ICG_STORES 
		set STATUS_SOURCE = TMP_IFRS17_ICG_STORES_RESVPIA.STATUS_SOURCE
		, INFORCE_FLAG = TMP_IFRS17_ICG_STORES_RESVPIA.INFORCE_FLAG
		, UPDATED_DATE=CURRENT_TIMESTAMP
		from STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA 
		where FOND_IFRS17_ICG_STORES.POLICY_NO = TMP_IFRS17_ICG_STORES_RESVPIA.POLICY_NO
		AND FOND_IFRS17_ICG_STORES.PRODUCT_CD = TMP_IFRS17_ICG_STORES_RESVPIA.PRODUCT_CD
		AND FOND_IFRS17_ICG_STORES.BENEFIT_CD = TMP_IFRS17_ICG_STORES_RESVPIA.BENEFIT_CD	
		AND FOND_IFRS17_ICG_STORES.CB_START_DT = TMP_IFRS17_ICG_STORES_RESVPIA.CB_START_DT
		AND FOND_IFRS17_ICG_STORES.CB_END_DT = TMP_IFRS17_ICG_STORES_RESVPIA.CB_END_DT	
		AND FOND_IFRS17_ICG_STORES.CREATED_DATE = TMP_IFRS17_ICG_STORES_RESVPIA.CREATED_DATE
		AND FOND_IFRS17_ICG_STORES.UPDATED_DATE = TMP_IFRS17_ICG_STORES_RESVPIA.UPDATED_DATE	
		AND lower(trim(FOND_IFRS17_ICG_STORES.SUBSYSTEM)) = lower(trim('Resvpia'))
		AND TMP_IFRS17_ICG_STORES_RESVPIA.ICG_FLAG = 'UPDATE EXISTING BUSINESS' 
		AND NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.INFORCE_FLAG),'') is not null
		AND NULLIF(TRIM(TMP_IFRS17_ICG_STORES_RESVPIA.STATUS_SOURCE),'') is not null
		;

		---------------------------------------------------
		--- Insert new valid records to ICG Stores Tables
		---------------------------------------------------
		-- insert log process
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'insert into FOND_ID.FOND_IFRS17_ICG_STORES for new business: ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		-- insert valid new records to icg stores
		INSERT INTO FOND_ID.FOND_IFRS17_ICG_STORES(
		ENTITY_ID
		,SYSTEM
		,POLICY_NO
		,PRODUCT_CD
		,BENEFIT_CD
		,CONTRACT_ID
		,PORTFOLIO_GROUP
		,COHORT_YEAR
		,SET_OF_CONTRACT
		,INSURANCE_CONTRACT_GROUP_ID
		,ICG_ID_PROPHET
		,ENTRY_MONTH
		,CB_START_DT
		,CB_END_DT
		,MEASUREMENT_MODEL
		,INFORCE_FLAG
		,COVERAGE_LEVEL_END_DATE
		,CCY_CD
		,STATUS_SOURCE
		,BEN_EXP_DATE
		,SUBSYSTEM
		,CREATED_DATE
		,UPDATED_DATE
		,BATCH_MASTER_ID 
		,BATCH_RUN_ID 
		,JOB_MASTER_ID
		,JOB_RUN_ID  
		,BATCHDATE
		,ETL_PROCESS_DATE_TIME 
		)
		SELECT 
		ENTITY_ID
		,SYSTEM
		,POLICY_NO
		,PRODUCT_CD
		,BENEFIT_CD
		,CONTRACT_ID
		,PORTFOLIO_GROUP
		,COHORT_YEAR
		,SET_OF_CONTRACT
		,INSURANCE_CONTRACT_GROUP_ID
		,ICG_ID_PROPHET
		,ENTRY_MONTH
		,CB_START_DT
		,(case when CB_END_DT <= BEN_EXP_DATE then CB_END_DT else BEN_EXP_DATE end)
		,MEASUREMENT_MODEL
		,INFORCE_FLAG
		,(case when COVERAGE_LEVEL_END_DATE <= BEN_EXP_DATE then COVERAGE_LEVEL_END_DATE else BEN_EXP_DATE end)
		,CCY_CD
		,STATUS_SOURCE
		,BEN_EXP_DATE
		,SUBSYSTEM
		,CREATED_DATE
		,UPDATED_DATE
		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		from STAG_ID.TMP_IFRS17_ICG_STORES_RESVPIA
		where ICG_FLAG =  'NEW BUSINESS'
		AND (case 	
			when NULLIF(TRIM(POLICY_NO),'') is null then 'N'
			when NULLIF(TRIM(PRODUCT_CD),'') is null then 'N'
			when NULLIF(TRIM(BENEFIT_CD),'') is null then 'N'
			when NULLIF(TRIM(CONTRACT_ID),'') is null then 'N'
			when NULLIF(TRIM(PORTFOLIO_GROUP),'') is null then 'N'
			when COHORT_YEAR is null then 'N'
			when NULLIF(TRIM(SET_OF_CONTRACT),'') is null then 'N'
			when NULLIF(TRIM(INSURANCE_CONTRACT_GROUP_ID),'') is null then 'N'
			when ICG_ID_PROPHET is null then 'N'
			when ENTRY_MONTH is null then 'N'
			when CB_START_DT is null then 'N'
			when CB_END_DT is null then 'N'
			when NULLIF(TRIM(MEASUREMENT_MODEL),'') is null then 'N'
			when NULLIF(TRIM(INFORCE_FLAG),'') is null then 'N'
			when COVERAGE_LEVEL_END_DATE is null then 'N'
			when NULLIF(TRIM(CCY_CD),'') is null then 'N'
			when NULLIF(TRIM(STATUS_SOURCE),'') is null then 'N'
			when BEN_EXP_DATE is null then 'N'
			when CB_START_DT > BEN_EXP_DATE then 'N'
			ELSE 'Y'
		end) = 'Y'
		;

	

		
		--------------------------------------------------
		--- Create Report Table for MP Files based on valid records in ICG Stores
		---------------------------------------------------
		-- insert valid records
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'create table FOND_ID.FOND_IFRS17_MPFILES_RESVPIA: ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

	
		-- add new column to MP files for ifrs17 for valid icg stores
		--drop table if exists FCORE_ID.FOND_IFRS17_MPFILES_RESVPIA;
		/*
		CREATE TABLE FOND_ID.FOND_IFRS17_MPFILES_RESVPIA 
		WITH
		(
		 DISTRIBUTION = HASH(CHDRNUM)
		,CLUSTERED INDEX (CHDRNUM)
		)
		AS
		*/
		INSERT INTO FOND_ID.FOND_IFRS17_MPFILES_RESVPIA
		SELECT
		-- existing column from ipsupf_v2
		NULLIF(TRIM(ipsupf.CHDRNUM),'') AS CHDRNUM,
		ipsupf.CRTABLE,
		ipsupf.ANBCCD,
		ipsupf.SEX,
		ipsupf.PCESSTRM,
		ipsupf.INSTOT,
		ipsupf.SUMINS,
		ipsupf.MORTCLS,
		ipsupf.HOISSDTE,
		ipsupf.CRRCD,
		ipsupf.TOPUPAMNT,
		ipsupf.WDRAMNT,
		ipsupf.TTLFUND,
		ipsupf.PRCF,
		ipsupf.PREF,
		ipsupf.PRFF,
		ipsupf.PRMF,
		ipsupf.PDMF,
		ipsupf.STATCODE,
		ipsupf.SLSCNL,
		ipsupf.CHGDTE,
		ipsupf.CURYRTUP,
		ipsupf.TOPUPLAST,
		ipsupf.BILCHNL,
		ipsupf.CLNTCODE,
		ipsupf.CLTPHONE01,
		ipsupf.CLTPHONE02,
		ipsupf.LIFCNUM,
		ipsupf.AGNTNUM,
		ipsupf.AGTNAME,
		ipsupf.DTEAPP,
		ipsupf.DTETRM,
		ipsupf.TSALESUNT,
		ipsupf.UNITNUM,
		ipsupf.UNITNAME,
		ipsupf.REGION,
		ipsupf.PRMP,
		ipsupf.PRODCAT,
		ipsupf.TPDCLAIM,
		ipsupf.ADDR04CITY,
		ipsupf.ADDR05PROV,
		ipsupf.SPEF,
		ipsupf.SPMF,
		ipsupf.SPFF,
		ipsupf.SPCF,
		ipsupf.SPMP,
		ipsupf.SPDF,
		ipsupf.SPTTLAMNT,
		ipsupf.TOPUPEF,
		ipsupf.TOPUPMF,
		ipsupf.TOPUPFF,
		ipsupf.TOPUPCF,
		ipsupf.TOPUPMP,
		ipsupf.TOPUPDF,
		ipsupf.TTTLTOPUP,
		ipsupf.WITHEF,
		ipsupf.WITHMF,
		ipsupf.WITHFF,
		ipsupf.WITHCF,
		ipsupf.WITHMP,
		ipsupf.WITHDF,
		ipsupf.TTLWITHAMT,
		ipsupf.LOADINGEXT,
		ipsupf.CLTDOB,
		ipsupf.MEDPRVIND,
		ipsupf.CNTCURR,
		ipsupf.ZZSRCE,
		ipsupf.UALPCTA,
		ipsupf.UALPCTB,
		ipsupf.UALPCTC,
		ipsupf.UALPCTD,
		ipsupf.UALPCTE,
		ipsupf.UALPCTF,
		ipsupf.CODE,
		ipsupf.ZLONGDESC,
		ipsupf.ACTVALUE,
		ipsupf.SURRDATE,
		ipsupf.LSTWDWDATE,
		ipsupf.LSTTOPDATE,
		ipsupf.PRGC,
		ipsupf.PDGC,
		ipsupf.SPRGC,
		ipsupf.SPDGC,
		ipsupf.TOPUPRGC,
		ipsupf.TOPUPGDC,
		ipsupf.WITHRGC,
		ipsupf.WITHDGC,
		ipsupf.UALPCTG,
		ipsupf.UALPCTH,
		ipsupf.PREP,
		ipsupf.SPEP,
		ipsupf.TOPUPEP,
		ipsupf.WITHEP,
		ipsupf.UALPCTI,
		ipsupf.PRIEF,
		ipsupf.SPRIEF,
		ipsupf.TUPRIEF,
		ipsupf.WDPRIEF,
		ipsupf.PRIEFPCT,
		ipsupf.REGIONFLG,
		ipsupf.PRVEF,
		ipsupf.SPRVEF,
		ipsupf.TUPRVEF,
		ipsupf.WDPRVEF,
		ipsupf.PRVEFPCT,
		ipsupf.PRAEF,
		ipsupf.SPRAEF,
		ipsupf.TUPRAEF,
		ipsupf.WDPRAEF,
		ipsupf.PRAEFPCT,
		ipsupf.PDIEF,
		ipsupf.LBIND,
		ipsupf.BASPRCF,
		ipsupf.BASPREF,
		ipsupf.BASPRFF,
		ipsupf.BASPRMF,
		ipsupf.BASPDMF,
		ipsupf.BASPRMPF,
		ipsupf.BASPRGCEF,
		ipsupf.BASPDGCEF,
		ipsupf.BASPREPF,
		ipsupf.BASPRIE,
		ipsupf.BASPRVE,
		ipsupf.BASPRAE,
		ipsupf.TOPPRCF,
		ipsupf.TOPPREF,
		ipsupf.TOPPRFF,
		ipsupf.TOPPRMF,
		ipsupf.TOPPDMF,
		ipsupf.TOPPRMPF,
		ipsupf.TOPPRGCEF,
		ipsupf.TOPPDGCEF,
		ipsupf.TOPPREPF,
		ipsupf.TOPPRIE,
		ipsupf.TOPPRVE,
		ipsupf.TOPPRAE,
		ipsupf.TOTBASFUND,
		ipsupf.TOTTOPFUND,
		ipsupf.PDGV,
		ipsupf.PDGM,
		ipsupf.PRGV,
		ipsupf.PRGM,
		ipsupf.PREC,
		ipsupf.PSEC,
		ipsupf.PDMM,
		ipsupf.PDIF,
		ipsupf.PDNV,
		ipsupf.SPMM,
		ipsupf.SPIF,
		ipsupf.SPNV,
		ipsupf.TOPUPMM,
		ipsupf.TOPUPIF,
		ipsupf.TOPUPNV,
		ipsupf.WITHMM,
		ipsupf.WITHIF,
		ipsupf.WITHNV,
		ipsupf.UALPCTJ,
		ipsupf.UALPCTK,
		ipsupf.UALPCTL,
		ipsupf.BASPDMM,
		ipsupf.BASPDIF,
		ipsupf.BASPDNV,
		ipsupf.TOPPDMM,
		ipsupf.TOPPDIF,
		ipsupf.TOPPDNV,
		ipsupf.PDFI,
		ipsupf.SPFI,
		ipsupf.TOPUPFI,
		ipsupf.WITHFI,
		ipsupf.UALPCTM,
		ipsupf.BASPDFI,
		ipsupf.TOPPDFI,
		ipsupf.PRNV,
		ipsupf.SPPR,
		ipsupf.TOPUPPR,
		ipsupf.WITHPR,
		ipsupf.UALPCTN,
		ipsupf.BASPDPR,
		ipsupf.TOPPDPR,
		ipsupf.PDGT,
		ipsupf.SPGT,
		ipsupf.TOPUPGT,
		ipsupf.WITHGT,
		ipsupf.UALPCTO,
		ipsupf.BASPDGT,
		ipsupf.TOPPDGT,
		ipsupf.STAT_SECT,
		ipsupf.PRMI,
		ipsupf.SRMI,
		ipsupf.TOPUPRI,
		ipsupf.WITHRI,
		ipsupf.UALPCTP,
		ipsupf.BASPRMI,
		ipsupf.TOPPRMI,
		ipsupf.PDMI,
		ipsupf.SDMI,
		ipsupf.TOPUPDI,
		ipsupf.WITHDI,
		ipsupf.UALPCTQ,
		ipsupf.BASPDMI,
		ipsupf.TOPPDMI,
		ipsupf.FLAGS,
		ipsupf.PRDP,
	    ipsupf.SP_PRDP,
	    ipsupf.TU_PRDP,
	    ipsupf.WITH_PRDP,
	    ipsupf.PERC_PRDP,
	    ipsupf.BAS_PRDP,
	    ipsupf.TOP_PRDP

		-- additional ifrs17 report
		,b.IFRS_ONEROUS_GRP
		,(case when cast(FORMAT(@V_START_DATE,'yyyy') as numeric(4,0)) = a.COHORT_YEAR then a.ENTRY_MONTH
			   when a.COHORT_YEAR < 1997 then 13
			   when a.COHORT_YEAR is not null then (a.COHORT_YEAR-1997) + 14
		 end) as IFRS_CY_GRP
		,d.IFRS_PORT_GRP
		, CASE
            WHEN a.MEASUREMENT_MODEL = 'GMM' THEN 0
            WHEN a.MEASUREMENT_MODEL = 'VFA' THEN 1
          END AS IFRS_MEASURE_MODEL
		,a.COHORT_YEAR as BASIC_ENTRY_YEAR
		,a.ENTRY_MONTH as BASIC_ENTRY_MONTH
		,(CAST(FORMAT(a.CB_END_DT,'yyyy') AS NUMERIC(4,0))-CAST(FORMAT(a.CB_START_DT,'yyyy') AS NUMERIC(4,0)))*12
		+ (CAST(FORMAT(a.CB_END_DT,'MM') AS NUMERIC(2,0))-CAST(FORMAT(a.CB_START_DT,'MM') AS NUMERIC(2,0))) as IFRS_CB_TERM_M
		,(case when cast(FORMAT(@V_START_DATE,'yyyy') as numeric(4,0)) = a.COHORT_YEAR then a.ENTRY_MONTH when a.COHORT_YEAR is not null then 0 else null end) as MTHS_TO_SALE
		,a.INSURANCE_CONTRACT_GROUP_ID AS IFRS_ICG_ID
		,a.ICG_ID_PROPHET AS IFRS_ICG_ID_PROPHET
		,b.SUB_GROUP_ID
		,a.ENTITY_ID
		--,a.CCY_CD
		,a.CB_START_DT
		,a.CB_END_DT
		,(case when cast(FORMAT(@V_START_DATE,'yyyy') as numeric(4,0)) = a.COHORT_YEAR then 
				NULLIF(TRIM(a.INSURANCE_CONTRACT_GROUP_ID),'')+'_'+NULLIF(UPPER(TRIM(a.ENTRY_MONTH_MMM)),'') end) 
		as REL_INSURANCE_CONTRACT_GROUP_ID
		-- additional ABC Framework columns
		,@BATCH_MASTER_ID as BATCH_MASTER_ID 
		,@BATCH_RUN_ID as BATCH_RUN_ID 
		,@JOB_MASTER_ID as JOB_MASTER_ID
		,@JOB_RUN_ID as JOB_RUN_ID  
		,@BATCHDATESTR as BATCHDATE
		,@GMT_START_DTTM as ETL_PROCESS_DATE_TIME 
		from STAG_ID.STAG_LIFEASIA_IPSUPF ipsupf
		left join (
			select x.*,
			CASE WHEN(ENTRY_MONTH =1) THEN 'JAN'
				WHEN(ENTRY_MONTH =2) THEN 'FEB'
				WHEN(ENTRY_MONTH =3) THEN 'MAR'
				WHEN(ENTRY_MONTH =4) THEN 'APR'
				WHEN(ENTRY_MONTH =5) THEN 'MAY'
				WHEN(ENTRY_MONTH =6) THEN 'JUN'
				WHEN(ENTRY_MONTH =7) THEN 'JUL'
				WHEN(ENTRY_MONTH =8) THEN 'AUG'
				WHEN(ENTRY_MONTH =9) THEN 'SEP'
				WHEN(ENTRY_MONTH =10) THEN 'OCT'
				WHEN(ENTRY_MONTH =11) THEN 'NOV'
				WHEN(ENTRY_MONTH =12) THEN 'DEC'
			END AS ENTRY_MONTH_MMM
			,row_number() over(partition by POLICY_NO 
			order by CB_START_DT desc, CB_END_DT desc, CREATED_DATE desc, UPDATED_DATE desc) as idx 
			FROM FOND_ID.FOND_IFRS17_ICG_STORES x
			where lower(trim(x.SUBSYSTEM)) = lower(trim('Resvpia'))
			AND PRODUCT_CD = BENEFIT_CD
		) a
		ON (CASE WHEN NULLIF(TRIM(ipsupf.CHDRNUM),'') IS NOT NULL THEN ipsupf.CHDRNUM ELSE 'N/A' END) = a.POLICY_NO AND a.idx = 1
		left join STAG_ID.STAG_CONFIG_IFRS17_ICG_CONFIG b 
		on a.PORTFOLIO_GROUP = b.PORTFOLIO_GROUP
		and a.MEASUREMENT_MODEL = b.MEASUREMENT_MODEL
		and (CASE WHEN (cast(a.COHORT_YEAR as numeric(4,0))) <'2006' THEN '2006' ELSE (cast(a.COHORT_YEAR as numeric(4,0))) END) = cast(b.COHORT_YEAR as numeric(4,0))
		and a.SET_OF_CONTRACT = b.SET_OF_CONTRACT

--		left join STAG_ID.STAG_CONFIG_IFRS17_PORTFOLIO_MAPPING c 
--		on a.PRODUCT_CD = c.PRODUCT_CD 
--		AND a.CCY_CD = c.CCY_CD 
--		AND UPPER(TRIM(CAST('Life Asia' AS VARCHAR(20)))) = UPPER(TRIM(c.SYSTEM))

		left join STAG_ID.STAG_CONFIG_IFRS17_PORTFOLIO_DETAILS d 
		on a.PORTFOLIO_GROUP = d.PORTFOLIO_GROUP 
		;

		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_END 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	='Finish ' + @V_FUNCTION_NAME + ' : ' +  convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION) VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		--IF @@TRANCOUNT > 0  
		--	COMMIT TRAN;

	END TRY

	BEGIN CATCH
		--IF @@TRANCOUNT > 0  
		--	ROLLBACK TRAN;
		
	    DECLARE @ErrorMessage AS NVARCHAR(1000)  = ERROR_MESSAGE()
		DECLARE @ErrorSeverity AS INT = ERROR_SEVERITY()
		DECLARE @ErrorState AS INT    = ERROR_STATE() 

	    SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_END 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	='Error execution for function on ' 
							+ @V_FUNCTION_NAME + ' at ' + convert(varchar,@V_START,121) 
							+ ' with Error Message : ' + ERROR_MESSAGE();
		PRINT @V_DESCRIPTION;
		INSERT into STAG_ID.STAG_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION) VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		RAISERROR(@ErrorMessage,@ErrorSeverity,@ErrorState)
	END CATCH

	
END;
