CREATE PROC [FOND_ID].[USP_LOAD_ETL5_FCT_CREATION_VALIDATION_DETAILS] @batch [nvarchar](30),@JOBNAMESTR [NVARCHAR](2000) AS
BEGIN 
	DECLARE @V_START		datetime;
	DECLARE @V_END			datetime;
	DECLARE @V_FUNCTION_NAME	NVARCHAR(2000) = 'FOND_ID.FOND_ETL5_FCT_CREATION_VALIDATION_DETAILS';
	DECLARE @V_DESCRIPTION	NVARCHAR(2000);
	DECLARE @V_CMD			NVARCHAR(2000);
	DECLARE @V_SEQNO			integer = 0;
	DECLARE @V_PRD_ID		integer;
	DECLARE @V_CREATED_DATE	datetime;
	DECLARE @V_START_DATE	date;
	DECLARE @V_END_DATE		date;
	
	BEGIN TRY

			------START GET RUN ID DETAIL FROM ABC------
		DECLARE 
		@BATCH_MASTER_ID  VARCHAR(20) = 0,
		@BATCH_RUN_ID    VARCHAR(20) = 0,
		@JOB_MASTER_ID   VARCHAR(20) = 0,
		@JOB_RUN_ID     VARCHAR(20) = 0,
		@GMT_START_DTTM   VARCHAR(19) = CONVERT(DATETIME2, GETDATE());

		EXEC STAG_ID.USP_GetRunIdReturn
		@JobName     = @JOBNAMESTR,
		@BATCH_MASTER_ID = @BATCH_MASTER_ID OUTPUT,
		@BATCH_RUN_ID  = @BATCH_RUN_ID OUTPUT,
		@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT,
		@JOB_RUN_ID   = @JOB_RUN_ID OUTPUT,
		@GMT_START_DTTM = @GMT_START_DTTM OUTPUT;
		------END GET RUN ID DETAIL FROM ABC------
		
		SET @V_START_DATE	= convert(date, cast(@batch as varchar(8))); -- valuation extract date
		PRINT	'Start date :' + convert(varchar,@V_START_DATE,112);
		SET @V_START 	= convert(datetime,getDATE());

		SET @V_DESCRIPTION 	= 'Start ' + @V_FUNCTION_NAME + ' : ' + convert(varchar,@V_START,121);
		PRINT	@V_DESCRIPTION;
		SET @V_SEQNO		= @V_SEQNO + 1;

		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		---------------------------- DROP TEMPORARY TABLE ------------------------------
		IF OBJECT_ID('tempdb..#SUNGL') IS NOT NULL
		BEGIN 
			DROP TABLE #SUNGL
		END;
		IF OBJECT_ID('tempdb..#NON_SUNGL') IS NOT NULL
		BEGIN
			DROP TABLE #NON_SUNGL
		END;		
		IF OBJECT_ID('tempdb..#SUBSET') IS NOT NULL
		BEGIN
			DROP TABLE #SUBSET
		END;

		---------------------------- INSERT INTO TEMPORARY TABLE ------------------------------
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'INSERT INTO TEMPORARY TABLE : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
	
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		SELECT *
		INTO #SUNGL
		FROM [STAG_ID].[STAG_CONFIG_ABST_FINANCE_CONFIG_HISTORICAL]
		WHERE BATCHDATE = left(@batch,6)
		AND PAS_NAME = 'SUNGL4'
		AND SOURCE_PARM_ID_1+SOURCE_PARM_ID_2+SOURCE_PARM_ID_3='***' 
		AND ACTION <> 'D';

		SELECT *
		INTO #NON_SUNGL
		FROM [STAG_ID].[STAG_CONFIG_ABST_FINANCE_CONFIG_HISTORICAL]
		WHERE BATCHDATE = left(@batch,6)
		AND PAS_NAME = '*'
		AND SOURCE_PARM_ID_1+SOURCE_PARM_ID_2+SOURCE_PARM_ID_3='***' 
		AND ACTION <> 'D';

		SELECT * 
		INTO #SUBSET
		FROM (
			SELECT * 
			FROM (
				SELECT 
					*,ROW_NUMBER() OVER(PARTITION BY SUN_CD ORDER BY PAS_NAME DESC) RN_PAS
				FROM (
					SELECT *,'' RN_FUND FROM #SUNGL
					UNION ALL
					SELECT * FROM (SELECT *,ROW_NUMBER() OVER(PARTITION BY SUN_CD ORDER BY FUND_CD ASC) RN_FUND FROM #NON_SUNGL) A 
					WHERE RN_FUND = 1
				) A
			) A
			WHERE RN_PAS = 1
		) A;

		---------------------------- DELETE Data ------------------------------
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'DELETE DATA FROM FOND_ID.FOND_ETL5_FCT_CREATION_VALIDATION_DETAILS : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
		
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
		
		DELETE FROM FOND_ID.FOND_ETL5_FCT_CREATION_VALIDATION_DETAILS WHERE BATCHDATE = left(@batch,6);
			
		---------------------------- Inserting data ------------------------------
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'INSERT INTO TABLE FOND_ID.FOND_ETL5_FCT_CREATION_VALIDATION_DETAILS : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
		
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);

		INSERT INTO FOND_ID.FOND_ETL5_FCT_CREATION_VALIDATION_DETAILS
		SELECT 
			a.ENTITY_ID, a.SUN_CD, a.FUND_CD, a.PAS_NAME, a.SOURCE_PARM_ID_1, a.SOURCE_PARM_ID_2, a.SOURCE_PARM_ID_3, a.CONTROL_ACCT_FLG, a.NEW_COA, a.CASHFLOW_TYPE_L1, a.CASHFLOW_TYPE_L2, a.VFA_CASHFLOW_TYPE, a.VFA_CASHFLOW_SIGNAGE, a.RN_FUND, a.RN_PAS, b.EXPENSE_IND, b.NON_ATTR_PCT, b.ACQUISTION_PCT, b.MAINTAIN_PCT, b.NON_PREM_MAINTAIN_PCT, b.RI_FLG, b.PCA_CATEGORY, b.CURR_IND, b.PRE_COV_PCT, b.PROFIT_MARGIN, b.INTERCOMP_IND, b.VALID_FLG, a.ACTION, a.USER_PROFILE, a.UPDATE_DT, 
			@BATCH_MASTER_ID AS BATCH_MASTER_ID,
			@BATCH_RUN_ID AS BATCH_RUN_ID,
			@JOB_MASTER_ID AS JOB_MASTER_ID,
			@JOB_RUN_ID AS JOB_RUN_ID,
			left(convert(varchar(8), @batch),6) as BATCHDATE,
			current_timestamp as ETL_PROCESS_DATE_TIME
		FROM #SUBSET a
		LEFT JOIN  (SELECT * FROM [FCORE_ID].[FOND_EXPENSE_CONFIG] WHERE CURR_IND = 'Y') b
		ON a.SUN_CD = b.SUN_CD;
		
		---------------------------- DROP TEMPORARY TABLE ------------------------------
		IF OBJECT_ID('tempdb..#SUNGL') IS NOT NULL
		BEGIN 
			DROP TABLE #SUNGL
		END;
		IF OBJECT_ID('tempdb..#NON_SUNGL') IS NOT NULL
		BEGIN
			DROP TABLE #NON_SUNGL
		END;		
		IF OBJECT_ID('tempdb..#SUBSET') IS NOT NULL
		BEGIN
			DROP TABLE #SUBSET
		END;		

	END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0
				ROLLBACK;
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_END 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	='Error execution for function on ' 
							+ @V_FUNCTION_NAME + ' at ' + convert(varchar,@V_START,121) 
							+ ' with Error Message : ' + ERROR_MESSAGE();
		PRINT @V_DESCRIPTION;
		
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION) VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
		raiserror(@V_DESCRIPTION, 18, 1)
	END CATCH
	
END;

