CREATE PROC [FOND_ID].[USP_LOAD_ETL5_SUNGL_EXTRACT_SPLITTING] @batch [NVARCHAR](100),@JOBNAMESTR [NVARCHAR](2000) AS
BEGIN 
	DECLARE @V_START		datetime;
	DECLARE @V_END			datetime;
	DECLARE @V_FUNCTION_NAME	NVARCHAR(2000) = 'FOND_ID.FOND_ETL5_SUNGL_EXTRACT';
	DECLARE @V_TABLE1 		NVARCHAR(2000);
	DECLARE @V_TABLE2 		NVARCHAR(2000);
	DECLARE @SCHEMA      NVARCHAR(MAX)
	DECLARE @V_DESCRIPTION	NVARCHAR(2000);
	DECLARE @V_CMD			NVARCHAR(2000);
	DECLARE @V_SEQNO			integer = 0;
	DECLARE @V_PRD_ID		integer;
	DECLARE @V_CREATED_DATE	datetime;
	DECLARE @V_START_DATE	date;
	DECLARE @V_END_DATE		date;
	DECLARE @drivername NVARCHAR(15);
	SET @drivername = 'SUNGL_EXT';
	DECLARE @V_DRIVER_PERIOD VARCHAR(10)=SUBSTRING(CAST(@batch AS VARCHAR),1,6); 
	DECLARE @acctcd_col varchar(20)= 'ACCT_CD';
	DECLARE @jrnaltype_col varchar(20)= 'JRNAL_TYPE';
	DECLARE @tref_col varchar(20)= 'TXN_REF';
	DECLARE @desc_col varchar(20)= 'TXN_DESC';
 	DECLARE @jrnalsrc_col varchar(20)= 'JRNAL_SRC' ;
 	DECLARE @t0_col varchar(20)= 'T0' ;
	
	------START GET RUN ID DETAIL FROM ABC------
	DECLARE 
	@BATCH_MASTER_ID  VARCHAR(20) = 0,
	@BATCH_RUN_ID    VARCHAR(20) = 0,
	@JOB_MASTER_ID   VARCHAR(20) = 0,
	@JOB_RUN_ID     VARCHAR(20) = 0,
	@GMT_START_DTTM   VARCHAR(19) = CONVERT(DATETIME2, GETDATE());

	EXEC STAG_ID.USP_GetRunIdReturn
	@JobName     = @JOBNAMESTR,
	@BATCH_MASTER_ID = @BATCH_MASTER_ID OUTPUT,
	@BATCH_RUN_ID  = @BATCH_RUN_ID OUTPUT,
	@JOB_MASTER_ID  = @JOB_MASTER_ID OUTPUT,
	@JOB_RUN_ID   = @JOB_RUN_ID OUTPUT,
	@GMT_START_DTTM = @GMT_START_DTTM OUTPUT;
	------END GET RUN ID DETAIL FROM ABC------


BEGIN TRY
		

		SET @V_START_DATE	= convert(date, cast(@batch as varchar)); -- valuation extract date
		PRINT	'Start date :' + convert(varchar,@V_START_DATE,112);
		SET @V_START 	= convert(datetime,getDATE());

		SET @V_DESCRIPTION 	= 'Start ' + @V_FUNCTION_NAME + ' : ' + convert(varchar,@V_START,121);
		PRINT	@V_DESCRIPTION;
		SET @V_SEQNO		= @V_SEQNO + 1;

		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
	
		---------------------------- DROP TEMPORARY TABLE ------------------------------
		IF OBJECT_ID('tempdb..#SUNGL_EXTRACT') IS NOT NULL
		BEGIN
			DROP TABLE #SUNGL_EXTRACT
		END;
		IF OBJECT_ID('tempdb..#EXCL') IS NOT NULL
		BEGIN
			DROP TABLE #EXCL
		END;
		IF OBJECT_ID('tempdb..#EXCL_FLAG') IS NOT NULL
		BEGIN
			DROP TABLE #EXCL_FLAG
		END;
		IF OBJECT_ID('tempdb..#INCL') IS NOT NULL
		BEGIN
			DROP TABLE #INCL
		END;
		IF OBJECT_ID('tempdb..#STEP1') IS NOT NULL
		BEGIN
			DROP TABLE #STEP1
		END;
		IF OBJECT_ID('tempdb..#STEP2') IS NOT NULL
		BEGIN
			DROP TABLE #STEP2
		END;
		IF OBJECT_ID('tempdb..#STEP3') IS NOT NULL
		BEGIN
			DROP TABLE #STEP3
		END;
		IF OBJECT_ID('tempdb..#STEP4') IS NOT NULL
		BEGIN
			DROP TABLE #STEP4
		END;
		IF OBJECT_ID('tempdb..#STEP5') IS NOT NULL
		BEGIN
			DROP TABLE #STEP5
		END;
		IF OBJECT_ID('tempdb..#STEP6') IS NOT NULL
		BEGIN
			DROP TABLE #STEP6
		END;
		IF OBJECT_ID('tempdb..#STEP7') IS NOT NULL
		BEGIN
			DROP TABLE #STEP7
		END;
		IF OBJECT_ID('tempdb..#STEP8') IS NOT NULL
		BEGIN
			DROP TABLE #STEP8
		END;
		IF OBJECT_ID('tempdb..#STEP9') IS NOT NULL
		BEGIN
			DROP TABLE #STEP9
		END;
		IF OBJECT_ID('tempdb..#STEP10a') IS NOT NULL
		BEGIN
			DROP TABLE #STEP10a
		END;
		IF OBJECT_ID('tempdb..#STEP10b') IS NOT NULL
		BEGIN
			DROP TABLE #STEP10b
		END;
		IF OBJECT_ID('tempdb..#STEP10c') IS NOT NULL
		BEGIN
			DROP TABLE #STEP10c
		END;
		IF OBJECT_ID('tempdb..#STEP11') IS NOT NULL
		BEGIN
			DROP TABLE #STEP11
		END;
		IF OBJECT_ID('tempdb..#STEP12') IS NOT NULL
		BEGIN
			DROP TABLE #STEP12
		END;
		IF OBJECT_ID('tempdb..#STEP13A') IS NOT NULL
		BEGIN
			DROP TABLE #STEP13A
		END;
        IF OBJECT_ID('tempdb..#STEP13B') IS NOT NULL
		BEGIN
			DROP TABLE #STEP13B
		END;
        IF OBJECT_ID('tempdb..#STEP13C') IS NOT NULL
		BEGIN
			DROP TABLE #STEP13C
		END;
		IF OBJECT_ID('tempdb..#STEP14') IS NOT NULL
		BEGIN
			DROP TABLE #STEP14
		END;
		IF OBJECT_ID('tempdb..#STEP15') IS NOT NULL
		BEGIN
			DROP TABLE #STEP15
		END;
		IF OBJECT_ID('tempdb..#STEP16') IS NOT NULL
		BEGIN
			DROP TABLE #STEP16
		END;
		IF OBJECT_ID('tempdb..#STEP17') IS NOT NULL
		BEGIN
			DROP TABLE #STEP17
		END;	
		IF OBJECT_ID('tempdb..#STEP18') IS NOT NULL
		BEGIN
			DROP TABLE #STEP18
		END;
		IF OBJECT_ID('tempdb..#STEP19') IS NOT NULL
		BEGIN
			DROP TABLE #STEP19
		END;	
		IF OBJECT_ID('tempdb..#SUNGL_EXTRACT') IS NOT NULL
		BEGIN
			DROP TABLE #SUNGL_EXTRACT
		END;
		IF OBJECT_ID('tempdb..#SUNGL_FINAL') IS NOT NULL
		BEGIN
			DROP TABLE #SUNGL_FINAL
		END;
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'SELECT INTO TEMPORARY TABLE etl5_sungl_extract : ' + @batch + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;

		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);		 


		---------------------------- INSERT INTO TEMPORARY TABLE ------------------------------
		SELECT DISTINCT A.PERIOD+A.ACCNT_CODE+A.JRNAL_TYPE ACCNT_LAS, JRNAL_TYPE
		-- DROP TABLE #EXCL
		INTO #EXCL
		FROM (
		SELECT DISTINCT A.* FROM (SELECT DISTINCT * FROM FOND_ID.FOND_ETL5_IFRS4_SUNGL
		WHERE ENTITY_ID IN ('IAC','IAS') AND SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2)+VALID_FROM = 
		(SELECT PERIOD+VALID_FROM FROM 
		(SELECT --RANK() OVER (PARTITION BY PERIOD ORDER BY VALID_FROM DESC) AS Rank,
		PERIOD, MAX(VALID_FROM) VALID_FROM FROM (
		SELECT DISTINCT PERIOD
		, VALID_FROM 
		-- SELECT *
		FROM FOND_ID.FOND_ETL5_IFRS4_SUNGL
		WHERE ENTITY_ID IN ('IAC','IAS') AND TRIM(PERIOD) = SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2)
		) A GROUP BY PERIOD) A 
		)) A WHERE ACCNT_CODE IN (
		SELECT DISTINCT EXCL_FIELD2_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @jrnaltype_col AND EXCL_FIELD2 = @acctcd_col
		)) A INNER JOIN (
		SELECT DISTINCT EXCL_FIELD2_COND,EXCL_FIELD1_COND,ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @jrnaltype_col AND EXCL_FIELD2 = @acctcd_col
		) B ON A.JRNAL_TYPE = B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID
		;
	
		-- SELECT * FROM #EXCL
		--DECLARE @batch [nvarchar](30);
		--SET @batch = '20190101';
	
		SELECT DISTINCT A.* 
		-- DROP TABLE #EXCL_FLAG
		INTO #EXCL_FLAG
		from (
		SELECT A.* from (SELECT * FROM FOND_ID.FOND_ETL5_IFRS4_SUNGL
		WHERE ENTITY_ID IN ('IAC','IAS') AND SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2)+VALID_FROM = 
		(SELECT PERIOD FROM 
		(
		
		SELECT PERIOD, MAX(VALID_FROM) VALID_FROM FROM (
		SELECT DISTINCT SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2)+VALID_FROM PERIOD
		, VALID_FROM  
		FROM FOND_ID.FOND_ETL5_IFRS4_SUNGL 
		WHERE TRIM(PERIOD) = SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2) AND ENTITY_ID IN ('IAC','IAS')
		) A GROUP BY PERIOD) A 
		)
		) A  
		WHERE
		PERIOD+ACCNT_CODE+JRNAL_TYPE NOT IN (
		SELECT DISTINCT ACCNT_LAS FROM #EXCL
		)) A
		;
		
		-----------------   INCLUSION   ----------------------------
		SELECT DISTINCT A.* INTO #INCL FROM (
		--DESCRIPTN
		SELECT A.* FROM (
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG WHERE ACCNT_CODE+JRNAL_TYPE IN (
		SELECT EXCL_FIELD1_COND+EXCL_FIELD2_COND 
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @jrnaltype_col)
		)) A INNER JOIN (
		SELECT EXCL_FIELD2_COND,ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @jrnaltype_col)
		) B ON A.JRNAL_TYPE LIKE   B.EXCL_FIELD2_COND AND A.ENTITY_ID = B.ENTITY_ID ) A
		WHERE A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN NOT IN (
		
		
				SELECT A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN FROM (
				SELECT * FROM #EXCL_FLAG) A INNER JOIN (
				SELECT EXCL_FIELD1_COND as EXCL_FIELD1_COND
				FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
				AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 IS NULL)
				B ON A.DESCRIPTN LIKE B.EXCL_FIELD1_COND  )
		AND A.ACCNT_CODE+A.TREFERENCE NOT IN (
		
				SELECT A.ACCNT_CODE+A.TREFERENCE FROM (
				SELECT * FROM #EXCL_FLAG WHERE ACCNT_CODE IN (
				SELECT DISTINCT EXCL_FIELD2_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
				WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
				AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @acctcd_col
				)) A INNER JOIN (
				SELECT DISTINCT EXCL_FIELD2_COND,EXCL_FIELD1_COND,ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
				WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
				AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @acctcd_col
				) B ON A.TREFERENCE LIKE B.EXCL_FIELD1_COND   OR A.TREFERENCE LIKE   B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID)
		
		
		UNION
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG WHERE ACCNT_CODE IN (
		SELECT EXCL_FIELD1_COND as EXCL_FIELD1_COND
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @desc_col)
		)) A INNER JOIN (
		SELECT EXCL_FIELD2_COND,EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @desc_col)
		) B ON A.DESCRIPTN LIKE   B.EXCL_FIELD2_COND   and A.ACCNT_CODE=B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID
		
		UNION
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG WHERE ACCNT_CODE IN (
		SELECT EXCL_FIELD1_COND 
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @tref_col)
		)) A INNER JOIN (
		SELECT EXCL_FIELD2_COND,EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @tref_col)
		) B ON A.TREFERENCE LIKE B.EXCL_FIELD2_COND   and A.ACCNT_CODE=B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID

		UNION 
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG WHERE ACCNT_CODE IN (
		SELECT EXCL_FIELD1_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @jrnaltype_col AND EXCL_SUMMARY_DESC='IBNR')
		)) A INNER JOIN (
		SELECT EXCL_FIELD1_COND as EXCL_FIELD1_COND,EXCL_SUMMARY_DESC, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND (EXCL_FIELD2 = @jrnaltype_col AND EXCL_SUMMARY_DESC='IBNR')
		) B ON A.DESCRIPTN LIKE   B.EXCL_SUMMARY_DESC AND A.ENTITY_ID = B.ENTITY_ID
		
		UNION
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG WHERE ACCNT_CODE IN (
		SELECT EXCL_FIELD2_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 = @acctcd_col
		) ) A INNER JOIN (
		SELECT EXCL_FIELD2_COND,EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 = @acctcd_col
		) B ON A.DESCRIPTN = B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID
		
		UNION 
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+TREFERENCE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND as EXCL_FIELD1_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND (EXCL_FIELD2 = '' or  EXCL_FIELD2 is null))
		B ON A.TREFERENCE LIKE  B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID
		)
		
		UNION

		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+TREFERENCE+DESCRIPTN IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE+A.DESCRIPTN FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @desc_col)
		B ON A.TREFERENCE LIKE  B.EXCL_FIELD1_COND   and A.DESCRIPTN LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)
		
		UNION 
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+DESCRIPTN+TREFERENCE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN+A.TREFERENCE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 = @tref_col)
		B ON A.DESCRIPTN LIKE  B.EXCL_FIELD1_COND   and A.TREFERENCE LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)
		
 		UNION

		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+TREFERENCE+JRNAL_SRCE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE+A.JRNAL_SRCE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @jrnalsrc_col)
		B ON A.TREFERENCE LIKE  B.EXCL_FIELD1_COND   and A.JRNAL_SRCE LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)		
		UNION 
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+DESCRIPTN+JRNAL_SRCE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN+A.JRNAL_SRCE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 = @jrnalsrc_col)
		B ON A.DESCRIPTN LIKE  B.EXCL_FIELD1_COND   and A.JRNAL_SRCE LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)	
		union 

		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+TREFERENCE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @acctcd_col)
		B ON A.TREFERENCE LIKE  B.EXCL_FIELD1_COND   and A.ACCNT_CODE LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)
		UNION 

		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+JRNAL_SRCE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.JRNAL_SRCE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @jrnalsrc_col)
		B ON A.ACCNT_CODE LIKE  B.EXCL_FIELD1_COND   and A.JRNAL_SRCE LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)
		
		UNION
		
		SELECT DISTINCT A.* FROM (
		SELECT * FROM #EXCL_FLAG ) A WHERE ACCNT_CODE+PERIOD+TREFERENCE+JRNAL_TYPE IN (
		SELECT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE+A.JRNAL_TYPE FROM (
		SELECT * FROM #EXCL_FLAG) A INNER JOIN (
		SELECT EXCL_FIELD1_COND EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID
		FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG WHERE TRIM(EXCL_FLG) = 'INCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @jrnaltype_col)
		B ON A.TREFERENCE LIKE  B.EXCL_FIELD1_COND   and A.JRNAL_TYPE LIKE  B.EXCL_FIELD2_COND  AND A.ENTITY_ID = B.ENTITY_ID
		)
		
		UNION 

		SELECT *
		FROM #EXCL_FLAG WHERE ACCNT_CODE+PERIOD+JRNAL_TYPE IN 
		(
		SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.JRNAL_TYPE FROM #EXCL_FLAG A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, EXCL_FIELD2_COND,ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
		WHERE EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @jrnaltype_col and BIN_FLG='INCL' AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.ACCNT_CODE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.JRNAL_TYPE) LIKE  UPPER(TRIM(B.EXCL_FIELD2_COND)) AND A.ENTITY_ID = B.ENTITY_ID
		)
		
		) A
		;
		
		-- DROP TABLE #STEP1
		SELECT DISTINCT * 
		INTO #STEP1
		FROM #EXCL_FLAG WHERE ACCNT_CODE+JRNAL_TYPE NOT IN (
		SELECT EXCL_FIELD1_COND+EXCL_FIELD2_COND  FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @jrnaltype_col AND [ACTION] = 'I'
		)
		;
	
		-- DROP TABLE #STEP2
		SELECT DISTINCT * 
		INTO #STEP2
		FROM #STEP1 WHERE PERIOD+ACCNT_CODE+TREFERENCE NOT IN (
		SELECT DISTINCT A.PERIOD+A.ACCNT_CODE+A.TREFERENCE FROM (
		SELECT * FROM #STEP1 WHERE ACCNT_CODE IN (
		SELECT DISTINCT EXCL_FIELD1_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @tref_col AND ACTION = 'I'
		)) A INNER JOIN (
		SELECT DISTINCT EXCL_FIELD1_COND as EXCL_FIELD1_COND,EXCL_FIELD2_COND,ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @tref_col
		) B ON A.TREFERENCE LIKE  B.EXCL_FIELD2_COND AND A.ENTITY_ID = B.ENTITY_ID )
		;
 		
		-- DROP TABLE #STEP3
		SELECT DISTINCT * 
		INTO #STEP3
		FROM #STEP2 WHERE upper(PERIOD+ACCNT_CODE+DESCRIPTN) NOT IN (
		SELECT DISTINCT upper(A.PERIOD+A.ACCNT_CODE+A.DESCRIPTN) FROM (
		SELECT * FROM #STEP2 WHERE ACCNT_CODE IN (
		SELECT DISTINCT EXCL_FIELD1_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @desc_col
		)) A INNER JOIN (
		SELECT DISTINCT EXCL_FIELD1_COND as EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @desc_col
		) B ON UPPER(A.DESCRIPTN) LIKE  UPPER(B.EXCL_FIELD2_COND)   and A.ACCNT_CODE = B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID
		) 
		;


		-- DROP TABLE #STEP4
		SELECT DISTINCT * INTO #STEP4 FROM #STEP3 WHERE ACCNT_CODE NOT IN (
		SELECT DISTINCT EXCL_FIELD1_COND  FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 IS NULL
		)
		;
	
		-- DROP TABLE #STEP5
		SELECT DISTINCT * 
		INTO #STEP5
		FROM #STEP4 WHERE ACCNT_CODE+JRNAL_TYPE NOT IN (
		SELECT DISTINCT A.ACCNT_CODE+A.JRNAL_TYPE FROM (
		SELECT * FROM #STEP4 WHERE ACCNT_CODE IN (
		SELECT DISTINCT EXCL_FIELD1_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @jrnaltype_col AND [ACTION] = 'I'
		)) A INNER JOIN (
		SELECT DISTINCT EXCL_FIELD1_COND as EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID  FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @jrnaltype_col AND [ACTION] = 'I'
		) B ON A.JRNAL_TYPE = B.EXCL_FIELD2_COND AND A.ENTITY_ID = B.ENTITY_ID)
		;

		-- DROP TABLE #STEP6
		SELECT DISTINCT * 
		INTO #STEP6
		FROM #STEP5 WHERE ACCNT_CODE+DESCRIPTN NOT IN (
		SELECT DISTINCT A.ACCNT_CODE+A.DESCRIPTN FROM (
		SELECT * FROM #STEP5 WHERE ACCNT_CODE IN (
		SELECT DISTINCT EXCL_FIELD2_COND  FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 = @acctcd_col --AND EXCL_FIELD2_COND = '5111010000'
		)) A INNER JOIN (
		SELECT DISTINCT EXCL_FIELD2_COND,EXCL_FIELD1_COND, ENTITY_ID  FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @desc_col AND EXCL_FIELD2 = @acctcd_col
		) B ON A.DESCRIPTN LIKE  B.EXCL_FIELD1_COND  AND A.ENTITY_ID = B.ENTITY_ID)
		;
		
		-- DROP TABLE #STEP7
		SELECT DISTINCT * 
		INTO #STEP7
		FROM #STEP6 WHERE ACCNT_CODE+TREFERENCE NOT IN (
		SELECT A.ACCNT_CODE+A.TREFERENCE FROM (
		SELECT * FROM #STEP6 WHERE ACCNT_CODE IN (
		SELECT DISTINCT EXCL_FIELD2_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @acctcd_col
		)) A INNER JOIN (
		SELECT DISTINCT EXCL_FIELD2_COND,EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND ENTITY_ID IN ('IAC','IAS')
		AND EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @acctcd_col
		) B ON A.TREFERENCE LIKE B.EXCL_FIELD1_COND   OR A.TREFERENCE LIKE   B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID)
		;
	
		-- DROP TABLE #STEP8
		SELECT DISTINCT * INTO #STEP8 
		FROM #STEP7 WHERE ACCNT_CODE+PERIOD+DESCRIPTN NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN FROM #STEP7 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG
		WHERE EXCL_FIELD1 = @desc_col AND (EXCL_FIELD2 IS NULL or EXCL_FIELD2='') AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.DESCRIPTN) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND))  AND A.ENTITY_ID = B.ENTITY_ID
		)
		;
		
		-- DROP TABLE #STEP9
		SELECT DISTINCT * 
		INTO #STEP9
		FROM #STEP8 WHERE ACCNT_CODE NOT IN (
		SELECT DISTINCT EXCL_FIELD1_COND FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
--		WHERE EXCL_FIELD2_COND IS NULL --AND EXCL_FIELD1_COND = '5119030000' 
		WHERE EXCL_FIELD1=@acctcd_col and (EXCL_FIELD2_COND IS NULL or EXCL_FIELD2_COND='') and BIN_FLG='EXCL' and ACTION='I' AND ENTITY_ID IN ('IAC','IAS')
		)
		;


		-- DROP TABLE #STEP10a
		SELECT distinct A.* 
		INTO #STEP10a
		FROM (
		SELECT * FROM #STEP9 A
		WHERE A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN NOT IN (	
		SELECT A.ACCNT_CODE+A.PERIOD+A.DESCRIPTN FROM (		
		SELECT DISTINCT * 
				--INTO #STEP10
				FROM #STEP9
				WHERE ACCNT_CODE IN (
				SELECT DISTINCT EXCL_FIELD1_COND as EXCL_FIELD1_COND
				--,ACTION,UPDATE_DATE 
				FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
				WHERE EXCL_FIELD2_COND IS NOT NULL and EXCL_FIELD2=@desc_col AND ENTITY_ID IN ('IAC','IAS') --AND EXCL_FIELD1_COND = '5119030000' 
				)) A
				INNER JOIN (SELECT DISTINCT UPPER(EXCL_FIELD2_COND ) EXCL_FIELD2_COND,UPPER(EXCL_FIELD1_COND) EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
				WHERE EXCL_FIELD2_COND IS NOT NULL  and EXCL_FIELD2=@desc_col AND ENTITY_ID IN ('IAC','IAS')) B ON UPPER(A.DESCRIPTN) LIKE  B.EXCL_FIELD2_COND   and A.ACCNT_CODE=B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID)
			) A
				;	

		-- DROP TABLE #STEP10b
		SELECT distinct A.* 
		INTO #STEP10b
		FROM (
		--ACCT_CD +JRNAL SRC
		SELECT * FROM #STEP10a A
		WHERE A.ACCNT_CODE+A.PERIOD+A.JRNAL_SRCE NOT IN (	 
		SELECT A.ACCNT_CODE+A.PERIOD+A.JRNAL_SRCE FROM (		
		SELECT DISTINCT * 
				FROM #STEP10a
				WHERE ACCNT_CODE IN (
				SELECT DISTINCT EXCL_FIELD1_COND as EXCL_FIELD1_COND
				FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
				WHERE EXCL_FIELD2_COND IS NOT NULL and EXCL_FIELD2=@jrnalsrc_col AND ENTITY_ID IN ('IAC','IAS') --AND EXCL_FIELD1_COND = '5119030000' 
				)) A
				INNER JOIN (SELECT DISTINCT UPPER(EXCL_FIELD2_COND ) EXCL_FIELD2_COND,UPPER(EXCL_FIELD1_COND) EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
				WHERE EXCL_FIELD2_COND IS NOT NULL and EXCL_FIELD2=@jrnalsrc_col AND ENTITY_ID IN ('IAC','IAS')) B ON UPPER(A.JRNAL_SRCE) LIKE  B.EXCL_FIELD2_COND   and A.ACCNT_CODE=B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID)
			) A
				;

		-- DROP TABLE #STEP10c
		SELECT distinct A.* 
		INTO #STEP10c
		FROM (
		--ACCT_CD +JRNAL SRC
		SELECT * FROM #STEP10b A
		WHERE A.ACCNT_CODE+A.PERIOD+A.ANAL_T0 NOT IN (	 
		SELECT A.ACCNT_CODE+A.PERIOD+A.ANAL_T0 FROM (		
		SELECT DISTINCT * 
				FROM #STEP10a
				WHERE ACCNT_CODE IN (
				SELECT DISTINCT EXCL_FIELD1_COND as EXCL_FIELD1_COND
				FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
				WHERE EXCL_FIELD2_COND IS NOT NULL and EXCL_FIELD2=@t0_col AND ENTITY_ID IN ('IAC','IAS')
				)) A
				INNER JOIN (SELECT DISTINCT UPPER(EXCL_FIELD2_COND ) EXCL_FIELD2_COND,UPPER(EXCL_FIELD1_COND) EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
				WHERE EXCL_FIELD2_COND IS NOT NULL and EXCL_FIELD2=@t0_col AND ENTITY_ID IN ('IAC','IAS')) B ON UPPER(A.ANAL_T0) LIKE  B.EXCL_FIELD2_COND   and A.ACCNT_CODE=B.EXCL_FIELD1_COND AND A.ENTITY_ID = B.ENTITY_ID)
			) A
				;	

		-- DROP TABLE #STEP11
		SELECT DISTINCT * 
		INTO #STEP11
		FROM #STEP10c WHERE JRNAL_TYPE NOT IN (	
		SELECT DISTINCT EXCL_FIELD1_COND FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG	
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND EXCL_FIELD1 = @jrnaltype_col AND (EXCL_FIELD2 IS NULL or EXCL_FIELD2='') AND ENTITY_ID IN ('IAC','IAS'))
		;
		-- DROP TABLE #STEP12
		SELECT DISTINCT * INTO #STEP12
		FROM #STEP11 WHERE ACCNT_CODE+PERIOD+TREFERENCE NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE FROM #STEP11 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG
		WHERE EXCL_FIELD1 = @tref_col AND (EXCL_FIELD2 IS NULL or EXCL_FIELD2='') AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.TREFERENCE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) AND A.ENTITY_ID = B.ENTITY_ID  
		)
		;
		
		-- DROP TABLE #STEP13A
		SELECT DISTINCT * INTO #STEP13A
		FROM #STEP12 WHERE ACCNT_CODE+PERIOD+TREFERENCE NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE FROM #STEP12 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
		WHERE EXCL_FIELD1 = @tref_col AND (EXCL_FIELD2 IS NULL or EXCL_FIELD2='') AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.TREFERENCE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) AND A.ENTITY_ID = B.ENTITY_ID 
		)
		;

        -- DROP TABLE #STEP13B
		SELECT DISTINCT * INTO #STEP13B
		FROM #STEP13A WHERE ACCNT_CODE+PERIOD+JRNAL_TYPE NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.JRNAL_TYPE FROM #STEP13A A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
		WHERE EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @jrnaltype_col AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.ACCNT_CODE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.JRNAL_TYPE) LIKE  UPPER(TRIM(B.EXCL_FIELD2_COND)) AND A.ENTITY_ID = B.ENTITY_ID
		)
		;
		
        -- DROP TABLE #STEP13C
		SELECT DISTINCT * INTO #STEP13C
		FROM #STEP13B WHERE ACCNT_CODE+PERIOD NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD FROM #STEP13B A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG
		WHERE TRIM(EXCL_FLG) = 'EXCL' AND EXCL_FIELD1 = @acctcd_col AND TRIM(COALESCE(EXCL_FIELD2, '')) = '' AND ENTITY_ID IN ('IAC','IAS')) 
		B ON UPPER(A.ACCNT_CODE) LIKE UPPER(TRIM(B.EXCL_FIELD1_COND))  AND A.ENTITY_ID = B.ENTITY_ID
		)
		;
		
		-- DROP TABLE #STEP14
		SELECT DISTINCT * INTO #STEP14
		FROM #STEP13C WHERE DESCRIPTN+PERIOD+TREFERENCE NOT IN 
		(SELECT DISTINCT A.DESCRIPTN+A.PERIOD+A.TREFERENCE FROM #STEP13C A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' and EXCL_FIELD1 = @desc_col AND EXCL_FIELD2=@tref_col AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.DESCRIPTN) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.TREFERENCE) LIKE  UPPER(TRIM(B.EXCL_FIELD2_COND)) AND A.ENTITY_ID = B.ENTITY_ID
		)
		
		-- DROP TABLE #STEP15
		SELECT DISTINCT * INTO #STEP15
		FROM #STEP14 WHERE ACCNT_CODE+PERIOD+TREFERENCE NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.TREFERENCE FROM #STEP14 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
		WHERE EXCL_FIELD1 = @acctcd_col AND EXCL_FIELD2 = @tref_col AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.ACCNT_CODE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.TREFERENCE) LIKE  UPPER(TRIM(B.EXCL_FIELD2_COND)) AND A.ENTITY_ID = B.ENTITY_ID
		)
		;

		-- DROP TABLE #STEP16
		SELECT DISTINCT * INTO #STEP16
		FROM #STEP15 WHERE JRNAL_TYPE+PERIOD+DESCRIPTN NOT IN 
		(SELECT DISTINCT A.JRNAL_TYPE+A.PERIOD+A.DESCRIPTN FROM #STEP15 A 
		INNER JOIN (
		SELECT DISTINCT EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' and EXCL_FIELD1 = @jrnaltype_col AND EXCL_FIELD2=@desc_col AND ENTITY_ID IN ('IAC','IAS')) B 
		ON UPPER(A.JRNAL_TYPE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.DESCRIPTN) LIKE UPPER(TRIM(B.EXCL_FIELD2_COND))  AND A.ENTITY_ID = B.ENTITY_ID
		);
		
		-- DROP TABLE #STEP17
		SELECT DISTINCT * INTO #STEP17
		FROM #STEP16 WHERE ACCNT_CODE+PERIOD+JRNAL_SRCE NOT IN 
		(SELECT DISTINCT A.ACCNT_CODE+A.PERIOD+A.JRNAL_SRCE FROM #STEP16 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
		WHERE EXCL_FIELD1 = @jrnalsrc_col AND (EXCL_FIELD2 IS NULL or EXCL_FIELD2='') AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.JRNAL_SRCE) LIKE UPPER(TRIM(B.EXCL_FIELD1_COND)) AND A.ENTITY_ID = B.ENTITY_ID
		);	
		
			-- DROP TABLE #STEP18
		SELECT DISTINCT * INTO #STEP18
		FROM #STEP17 WHERE TREFERENCE+PERIOD+DESCRIPTN NOT IN 
		(SELECT DISTINCT A.TREFERENCE+A.PERIOD+A.DESCRIPTN FROM #STEP17 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND,EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_EXCLUSION_CONFIG 
		WHERE TRIM(EXCL_FLG) = 'EXCL' and EXCL_FIELD1 = @tref_col AND EXCL_FIELD2= @desc_col AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.TREFERENCE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.DESCRIPTN) LIKE  UPPER(TRIM(B.EXCL_FIELD2_COND))  AND A.ENTITY_ID = B.ENTITY_ID
		);

		-- DROP TABLE #STEP19
		SELECT DISTINCT * INTO #STEP19
		FROM #STEP18 WHERE TREFERENCE+PERIOD+DESCRIPTN NOT IN 
		(SELECT DISTINCT  A.TREFERENCE+A.PERIOD+A.DESCRIPTN FROM #STEP18 A INNER JOIN
		(
		SELECT DISTINCT EXCL_FIELD1_COND, EXCL_FIELD2_COND, ENTITY_ID FROM FOND_ID.FOND_ETL5_BIN_ACCOUNT_CONFIG
		WHERE EXCL_FIELD1 = @tref_col AND EXCL_FIELD2 = @desc_col AND ENTITY_ID IN ('IAC','IAS'))
		B ON UPPER(A.TREFERENCE) LIKE  UPPER(TRIM(B.EXCL_FIELD1_COND)) and UPPER(A.DESCRIPTN) LIKE  UPPER(TRIM(B.EXCL_FIELD2_COND)) AND A.ENTITY_ID = B.ENTITY_ID
		)
		;
		
		-- DROP TABLE #SUNGL_EXTRACT
		SELECT DISTINCT A.* 
		INTO #SUNGL_EXTRACT
		FROM (
		SELECT DISTINCT * FROM #STEP19
		UNION 
		SELECT DISTINCT * FROM #INCL) A
		;
--DECLARE @batch [nvarchar](30);
--SET @batch = '20201001';	
		SELECT DISTINCT ENTITY_ID,ACCNT_CODE
		,PERIOD,convert(date,TRANS_DATE,103) TRANS_DATE
		--,CAST(AMOUNT AS NUMERIC(13,6)) AMOUNT
		,AMOUNT
		,D_C,CAST(JRNAL_NO AS VARCHAR(30)) JRNAL_NO,JRNAL_LINE,JRNAL_TYPE
		,JRNAL_SRCE,TREFERENCE,DESCRIPTN
		,ANAL_T0
		,ANAL_T1,ANAL_T2,ANAL_T3,ANAL_T4,ANAL_T5,ANAL_T6,ANAL_T7,ANAL_T8
		,@BATCH_MASTER_ID AS BATCH_MASTER_ID
		,@BATCH_RUN_ID AS BATCH_RUN_ID
		,@JOB_MASTER_ID AS JOB_MASTER_ID
		,@JOB_RUN_ID AS JOB_RUN_ID
		,SUBSTRING( CAST(@batch AS VARCHAR),1,6) BATCHDATE
		,GETDATE() ETL_PROCESS_DATE_TIME 
		INTO #SUNGL_FINAL
		FROM #SUNGL_EXTRACT
		where PERIOD=SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2)
		;
	
		---------------------------- TO Handle rerun process ------------------------------
		BEGIN TRANSACTION;
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'DELETE DATA FROM FOND_ID.[FOND_ETL5_SUNGL_EXTRACT] : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
		
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);	 


--DECLARE @batch [nvarchar](30);
--SET @batch = '20201201';			
		DELETE FROM FOND_ID.FOND_ETL5_SUNGL_EXTRACT 
		WHERE EXTRACT_PERIOD =  SUBSTRING(CAST(@batch AS VARCHAR),1,4)+'/0'+SUBSTRING(CAST(@batch AS VARCHAR),5,2) AND ENTITY_ID IN ('IAC','IAS');

		 ---------------------------- TO Handle rerun process ------------------------------
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'INSERT INTO TABLE FOND_ID.[FOND_ETL5_SUNGL_EXTRACT] : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
		
--DECLARE @batch [nvarchar](30);
--SET @batch = '20201201';	
		INSERT INTO [FOND_ID].[FOND_ETL5_SUNGL_EXTRACT]
		SELECT 
		ENTITY_ID
		,ACCNT_CODE
		,PERIOD
		,TRANS_DATE
		,AMOUNT
		,D_C
		,JRNAL_NO
		,JRNAL_LINE
		,JRNAL_TYPE
		,JRNAL_SRCE
		,TREFERENCE
		,DESCRIPTN
		,ANAL_T0
		,ANAL_T1,ANAL_T2,ANAL_T3,ANAL_T4,ANAL_T5,ANAL_T6,ANAL_T7,ANAL_T8
		,BATCH_MASTER_ID
		,BATCH_RUN_ID
		,JOB_MASTER_ID
		,JOB_RUN_ID
		,BATCHDATE
		,ETL_PROCESS_DATE_TIME 
		FROM #SUNGL_FINAL
		;
	
		---------------------------- ETL5 LOGGING ----------------------------      
       	
		DECLARE @V_TOTAL_ROWS integer = 0;
		DECLARE @V_PERIOD nvarchar(10);
		SET @V_TOTAL_ROWS = (SELECT COUNT(1) as totalrows FROM #SUNGL_FINAL) ;
        SET @V_PERIOD = CONCAT(YEAR(DATEADD(month, 0,CONVERT(date, @batch))), RIGHT(CONCAT('000', MONTH(DATEADD(month, 0,CONVERT(date, @batch)))),3))

		INSERT INTO FOND_ID.FOND_IFRS17_ETL5_PROC_LOG (PROC_DATE,FUNC_NAME,TRGT_TABLE_NAME,DRIVER_NAME,TOTAL_ROWS,DESCRIPTION,PERIOD)
		VALUES (@V_START,@V_FUNCTION_NAME,'FOND_ID.FOND_ETL5_SUNGL_EXTRACT'
		,@drivername,@V_TOTAL_ROWS,'MTD',@V_PERIOD);
		
	
		IF @@TRANCOUNT > 0
        COMMIT;


		---------------------------- DROP TEMPORARY TABLE ------------------------------  
		IF OBJECT_ID('tempdb..#SUNGL_FINAL') IS NOT NULL
		BEGIN
			DROP TABLE #SUNGL_FINAL
		END;

END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0
                ROLLBACK;
	    SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_END 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	='Error execution for function on ' 
							+ @V_FUNCTION_NAME + ' at ' + convert(varchar,@V_START,121) 
							+ ' with Error Message : ' + ERROR_MESSAGE();
		PRINT @V_DESCRIPTION;
		
		
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION) VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
		raiserror(@V_DESCRIPTION, 18, 1)
	END CATCH
END;



