CREATE PROC [FOND_ID].[USP_LOAD_ETL5_NO_OF_STAFF_STEP2_TESTING] @batchdate [varchar](12),@NB_OUT [varchar](100) OUT,@EB_OUT [varchar](100) OUT AS
BEGIN
	DECLARE  @V_TNAME_NB VARCHAR(100) = 'FOND_ID.FOND_ETL5_tTEMP_NO_STAFF_PRODUCT_NB_'+@batchdate
	set @NB_OUT=@V_TNAME_NB
	DECLARE  @V_TNAME_EB VARCHAR(100) = 'FOND_ID.FOND_ETL5_tTEMP_NO_STAFF_PRODUCT_EB_'+@batchdate
	set @EB_OUT=@V_TNAME_NB
END 
