/****** Object:  StoredProcedure [FOND_ID].[USP_LOAD_ETL5_LIFEASIA_MASTER_T0]    Script Date: 02/08/2024 18:26:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [FOND_ID].[USP_LOAD_ETL5_LIFEASIA_MASTER_T0] @batch [NVARCHAR](100),@JOBNAMESTR [NVARCHAR](2000) AS
BEGIN 
	--DECLARE @batch [nvarchar](30);
	DECLARE @V_START		datetime;
	DECLARE @V_END			datetime;
	DECLARE @V_FUNCTION_NAME	NVARCHAR(2000) = 'FOND_ID.FOND_ETL5_LIFEASIA_MASTER_T0';
	DECLARE @V_TABLE1 		NVARCHAR(2000);
	DECLARE @V_TABLE2 		NVARCHAR(2000);
	DECLARE @SCHEMA      NVARCHAR(MAX)
	DECLARE @V_DESCRIPTION	NVARCHAR(2000);
	DECLARE @V_CMD			NVARCHAR(2000);
	DECLARE @V_SEQNO			integer = 0;
	DECLARE @V_PRD_ID		integer;
	DECLARE @V_CREATED_DATE	datetime;
	DECLARE @V_START_DATE	date;
	DECLARE @V_END_DATE		date;
	DECLARE @drivername NVARCHAR(15);	
	SET @drivername = 'T0';
	DECLARE @V_DRIVER_PERIOD VARCHAR(10); 
	SET @V_DRIVER_PERIOD =SUBSTRING(CAST(@batch AS VARCHAR),1,6);
	--DECLARE @V_TNAME_EB VARCHAR(100) = 'FOND_ID.FOND_LIFEASIA_ETL4_LIFEASIA_'+@V_DRIVER_PERIOD;
	DECLARE @V_TNAME_EB VARCHAR(100) = 'FOND_ID.FOND_LIFEASIA_ETL4_LIFEASIA_'+@V_DRIVER_PERIOD+'_HIS';
	DECLARE @V_TNAME_EB1 VARCHAR(100) = 'FOND_ID.FOND_LIFEASIA_ETL4_LIFEASIA_INVALID_'+@V_DRIVER_PERIOD;
	--DECLARE @V_TNAME_EB2 VARCHAR(100) = 'FOND_ID.FOND_LIFEASIA_ETL4_LIFEASIA_NONRELATED_'+@V_DRIVER_PERIOD;
	DECLARE @V_TNAME_EB2 VARCHAR(100) = 'FOND_ID.FOND_LIFEASIA_ETL4_LIFEASIA_NONRELATED_'+@V_DRIVER_PERIOD+'_HIS';

	------ START ABC ------
	DECLARE
    @BATCH_MASTER_ID    VARCHAR(20) = 0,
    @BATCH_RUN_ID       VARCHAR(20) = 0,
    @JOB_MASTER_ID      VARCHAR(20) = 0,
    @JOB_RUN_ID         VARCHAR(20) = 0,
    @GMT_START_DTTM     VARCHAR(20) = GETDATE();
	
	EXEC STAG_ID.USP_GetRunIdReturn
	  @JobName        = @JOBNAMESTR,
	  @BATCH_MASTER_ID = @BATCH_MASTER_ID OUTPUT,
	  @BATCH_RUN_ID    = @BATCH_RUN_ID OUTPUT,
	  @JOB_MASTER_ID   = @JOB_MASTER_ID OUTPUT,
	  @JOB_RUN_ID      = @JOB_RUN_ID OUTPUT,
	  @GMT_START_DTTM  = @GMT_START_DTTM OUTPUT;
	------END GET RUN ID DETAIL FROM ABC--------- 	
	
 

		SET @SCHEMA ='FOND_ID.'
		SET @V_TABLE1 = 'FOND_ID.FOND_LIFEASIA_ETL4_LIFEASIA_' + SUBSTRING(CAST(@batch AS VARCHAR),1,6);
		SET @V_TABLE2 = 'FOND_LIFEASIA_ETL4_LIFEASIA_INVALID_' + SUBSTRING(CAST(@batch AS VARCHAR),1,6);

		SET @V_START_DATE	= convert(date, cast(@batch as varchar)); -- valuation extract date
		PRINT	'Start date :' + convert(varchar,@V_START_DATE,112);
		SET @V_START 	= convert(datetime,getDATE());

		SET @V_DESCRIPTION 	= 'Start ' + @V_FUNCTION_NAME + ' : ' + convert(varchar,@V_START,121);
		PRINT	@V_DESCRIPTION;
		SET @V_SEQNO		= @V_SEQNO + 1;

		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);
	
		---------------------------- DROP TEMPORARY TABLE ------------------------------
		IF OBJECT_ID('tempdb..#etl5_las_master_t0') IS NOT NULL
		BEGIN
			DROP TABLE #etl5_las_master_t0
		END;
		IF OBJECT_ID('tempdb..#T0') IS NOT NULL
		BEGIN
			DROP TABLE #T0
		END;
		

		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'SELECT INTO TEMPORARY TABLE etl5_las_master_t0 : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;

		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);		 


		---------------------------- INSERT INTO TEMPORARY TABLE ------------------------------
		
		
		--drop table IF EXISTS #T0;
		DECLARE @sql_selectTEB VARCHAR(8000)=
		'select a.* 
		into #T0
		from (
		select ACCT_PERIOD,PRODUCT_CD,BENEFIT_CD,T0 from '+@V_TNAME_EB+' WHERE T0 not in (''-'',''0000LAS'',''ITYT000'',''0000000'',''ITLS000'') 
		union 
		select ACCT_PERIOD,PRODUCT_CD,BENEFIT_CD,T0 from '+@V_TNAME_EB1+' 
		union
		select ACCT_PERIOD,PRODUCT_CD,BENEFIT_CD,T0 from '+@V_TNAME_EB2+' WHERE T0 not in (''-'',''0000LAS'',''ITYT000'',''0000000'',''ITLS000'')
		) a';
		--Create Dynamic table for
		EXEC( @sql_selectTEB);
		
		
		
		SELECT * 
		INTO #etl5_las_master_t0
		FROM #T0
		WHERE PRODUCT_CD IS NOT NULL
		;
		
	
		---------------------------- TO Handle rerun process ------------------------------
		BEGIN TRANSACTION;
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'DELETE DATA FROM FOND_ID.[FOND_ETL5_LIFEASIA_MASTER_T0] : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
		
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);	 

		-- SELECT DISTINCT DRIVER_PERIOD FROM FOND_ID.FOND_ETL5_LIFEASIA_MASTER_T0
	
		DELETE FROM FOND_ID.FOND_ETL5_LIFEASIA_MASTER_T0 
		WHERE ACCT_PERIOD =  YEAR(DATEADD(month, 0,CONVERT(date, @batch))) * 1000 + 0 + MONTH(DATEADD(month, 0,CONVERT(date, @batch)));

		 ---------------------------- TO Handle rerun process ------------------------------
		SET @V_SEQNO 	= @V_SEQNO + 1;
		SET @V_START 	= convert(datetime,getDATE());
		SET @V_DESCRIPTION	= 'INSERT INTO TABLE FOND_ID.[FOND_ETL5_LIFEASIA_MASTER_T0] : ' + convert(varchar,@V_START,121);
		PRINT @V_DESCRIPTION;
		INSERT into FOND_ID.FOND_IFRS17_PROC_LOG(PROC_DATE,FUNC_NAME,SEQNO,DESCRIPTION)
		VALUES (@V_START,@V_FUNCTION_NAME,@V_SEQNO,@V_DESCRIPTION);


		INSERT INTO [FOND_ID].[FOND_ETL5_LIFEASIA_MASTER_T0]
		SELECT CAST(ACCT_PERIOD AS VARCHAR) ACCT_PERIOD ,PRODUCT_CD,BENEFIT_CD,	T0,
				@BATCH_MASTER_ID AS BATCH_MASTER_ID,
				@BATCH_RUN_ID AS BATCH_RUN_ID,
				@JOB_MASTER_ID AS JOB_MASTER_ID,
				@JOB_RUN_ID AS JOB_RUN_ID,
				SUBSTRING( CAST(@batch AS VARCHAR),1,6) BATCHDATE,
				GETDATE() ETL_PROCESS_DATE_TIME 
		FROM #etl5_las_master_t0
		;
	
		---------------------------- ETL5 LOGGING ----------------------------      
       	
		DECLARE @V_TOTAL_ROWS integer = 0;
		DECLARE @V_PERIOD nvarchar(10);
		SET @V_TOTAL_ROWS = (SELECT COUNT(1) as totalrows FROM #etl5_las_master_t0) ;
        SET @V_PERIOD = CONCAT(YEAR(DATEADD(month, 0,CONVERT(date, @batch))), RIGHT(CONCAT('000', MONTH(DATEADD(month, 0,CONVERT(date, @batch)))),3))

		INSERT INTO FOND_ID.FOND_IFRS17_ETL5_PROC_LOG (PROC_DATE,FUNC_NAME,TRGT_TABLE_NAME,DRIVER_NAME,TOTAL_ROWS,DESCRIPTION,PERIOD)
		VALUES (@V_START,@V_FUNCTION_NAME,'FOND_ID.FOND_ETL5_LIFEASIA_MASTER_T0'
		,@drivername,@V_TOTAL_ROWS,'MTD',@V_PERIOD);
		
		SELECT 'Total records : ' + @V_PERIOD;

		IF @@TRANCOUNT > 0
        COMMIT;


		---------------------------- DROP TEMPORARY TABLE ------------------------------  
		IF OBJECT_ID('tempdb..#etl5_las_master_t0') IS NOT NULL
		BEGIN
			DROP TABLE #etl5_las_master_t0
		END;


	
END;
GO
